In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [2]:
reviews=pd.read_csv('reviews_details.csv')
listing=pd.read_csv('listings_details.csv')

In [3]:
listing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20030 entries, 0 to 20029
Data columns (total 96 columns):
id                                  20030 non-null int64
listing_url                         20030 non-null object
scrape_id                           20030 non-null int64
last_scraped                        20030 non-null object
name                                19992 non-null object
summary                             19510 non-null object
space                               14579 non-null object
description                         19906 non-null object
experiences_offered                 20030 non-null object
neighborhood_overview               13257 non-null object
notes                               9031 non-null object
transit                             13635 non-null object
access                              12227 non-null object
interaction                         11974 non-null object
house_rules                         12571 non-null object
thumbnail_url                       0 non-null float64
medium_url                          0 non-null float64
picture_url                         20030 non-null object
xl_picture_url                      0 non-null float64
host_id                             20030 non-null int64
host_url                            20030 non-null object
host_name                           20026 non-null object
host_since                          20026 non-null object
host_location                       19991 non-null object
host_about                          11803 non-null object
host_response_time                  10547 non-null object
host_response_rate                  10547 non-null object
host_acceptance_rate                0 non-null float64
host_is_superhost                   20026 non-null object
host_thumbnail_url                  20026 non-null object
host_picture_url                    20026 non-null object
host_neighbourhood                  14222 non-null object
host_listings_count                 20026 non-null float64
host_total_listings_count           20026 non-null float64
host_verifications                  20030 non-null object
host_has_profile_pic                20026 non-null object
host_identity_verified              20026 non-null object
street                              20030 non-null object
neighbourhood                       18377 non-null object
neighbourhood_cleansed              20030 non-null object
neighbourhood_group_cleansed        0 non-null float64
city                                20026 non-null object
state                               19903 non-null object
zipcode                             19164 non-null object
market                              19988 non-null object
smart_location                      20030 non-null object
country_code                        20030 non-null object
country                             20030 non-null object
latitude                            20030 non-null float64
longitude                           20030 non-null float64
is_location_exact                   20030 non-null object
property_type                       20030 non-null object
room_type                           20030 non-null object
accommodates                        20030 non-null int64
bathrooms                           20020 non-null float64
bedrooms                            20022 non-null float64
beds                                20023 non-null float64
bed_type                            20030 non-null object
amenities                           20030 non-null object
square_feet                         406 non-null float64
price                               20030 non-null object
weekly_price                        2843 non-null object
monthly_price                       1561 non-null object
security_deposit                    13864 non-null object
cleaning_fee                        16401 non-null object
guests_included                     20030 non-null int64
extra_people                        20030 non-null object
minimum_nights                      20030 non-null int64
maximum_nights                      20030 non-null int64
calendar_updated                    20030 non-null object
has_availability                    20030 non-null object
availability_30                     20030 non-null int64
availability_60                     20030 non-null int64
availability_90                     20030 non-null int64
availability_365                    20030 non-null int64
calendar_last_scraped               20030 non-null object
number_of_reviews                   20030 non-null int64
first_review                        17624 non-null object
last_review                         17624 non-null object
review_scores_rating                17391 non-null float64
review_scores_accuracy              17381 non-null float64
review_scores_cleanliness           17383 non-null float64
review_scores_checkin               17369 non-null float64
review_scores_communication         17378 non-null float64
review_scores_location              17370 non-null float64
review_scores_value                 17371 non-null float64
requires_license                    20030 non-null object
license                             9 non-null object
jurisdiction_names                  19358 non-null object
instant_bookable                    20030 non-null object
is_business_travel_ready            20030 non-null object
cancellation_policy                 20030 non-null object
require_guest_profile_picture       20030 non-null object
require_guest_phone_verification    20030 non-null object
calculated_host_listings_count      20030 non-null int64
reviews_per_month                   17624 non-null float64
dtypes: float64(21), int64(13), object(62)
memory usage: 14.7+ MB

In [4]:
listdata = []
listfeat=list(listing.columns)
for item in listfeat:
    list1=[]
    list1.append(item)
    list1.append(str(listing[item].dtype))
    list1.append(listing[item].isna().sum())
    list1.append(round((listing[item].isna().sum()/len(listing))*100,2))
    list1.append(listing[item].nunique())
    list1.append(list(listing[item].value_counts().head(2).index))
    listdata.append(list1)

desc=pd.DataFrame(listdata,columns='dataFeatures dataType null nullPct unique uniqueSample'.split(' '))
desc

,dataFeatures,dataType,null,nullPct,unique,uniqueSample
0,id,int64,0,0.00,20030,"[19075070, 21005013]"
1,listing_url,object,0,0.00,20030,"[https://www.airbnb.com/rooms/12511210, https:..."
2,scrape_id,int64,0,0.00,1,[20181206172549]
3,last_scraped,object,0,0.00,2,"[2018-12-06, 2018-12-07]"
4,name,object,38,0.19,19503,"[Amsterdam, Amsterdam Appartement]"
5,summary,object,520,2.60,19003,[**brand new** Sleeping up to 2 guests in luxu...
6,space,object,5451,27.21,14227,[This gorgeous apartment is excellently design...
7,description,object,124,0.62,19648,[Hotel Jansen is a new Short Stay hotel in Ams...
8,experiences_offered,object,0,0.00,1,[none]
9,neighborhood_overview,object,6773,33.81,12029,[Oud West is close to the city-centre and clos...
10,notes,object,10999,54.91,7270,[Freshly made up beds and crispy towels (one p...
11,transit,object,6395,31.93,12944,[You have not experienced the Dutch culture tr...
12,access,object,7803,38.96,9615,[Guests are invited to enjoy the whole apartme...
13,interaction,object,8056,40.22,9634,"[Iamb&b will let you in, hand you the keys and..."
14,house_rules,object,7459,37.24,10681,[GENERAL HOUSE RULES Thanks for booking our pl...
15,thumbnail_url,float64,20030,100.00,0,[]
16,medium_url,float64,20030,100.00,0,[]
17,picture_url,object,0,0.00,19937,[https://a0.muscache.com/im/pictures/cb39c8f2-...
18,xl_picture_url,float64,20030,100.00,0,[]
19,host_id,int64,0,0.00,17264,"[65859990, 1464510]"
20,host_url,object,0,0.00,17264,"[https://www.airbnb.com/users/show/65859990, h..."
21,host_name,object,4,0.02,5915,"[Martijn, Michiel And Jane]"
22,host_since,object,4,0.02,2829,"[2016-04-05, 2011-12-02]"
23,host_location,object,39,0.19,550,"[Amsterdam, North Holland, Netherlands, Amster..."
24,host_about,object,8227,41.07,9467,"[Hi, I'm Martijn, \r\n\r\nWe are a team of pro..."
25,host_response_time,object,9483,47.34,4,"[within an hour, within a few hours]"
26,host_response_rate,object,9483,47.34,58,"[100%, 90%]"
27,host_acceptance_rate,float64,20030,100.00,0,[]
28,host_is_superhost,object,4,0.02,2,"[f, t]"
29,host_thumbnail_url,object,4,0.02,17240,[https://a0.muscache.com/im/pictures/user/5832...
30,host_picture_url,object,4,0.02,17240,[https://a0.muscache.com/im/pictures/user/5832...
31,host_neighbourhood,object,5808,29.00,87,"[Oud-West, De Pijp]"
32,host_listings_count,float64,4,0.02,43,"[1.0, 2.0]"
33,host_total_listings_count,float64,4,0.02,43,"[1.0, 2.0]"
34,host_verifications,object,0,0.00,354,"[['email', 'phone', 'reviews', 'jumio'], ['ema..."
35,host_has_profile_pic,object,4,0.02,2,"[t, f]"
36,host_identity_verified,object,4,0.02,2,"[f, t]"
37,street,object,0,0.00,103,"[Amsterdam, Noord-Holland, Netherlands, Amster..."
38,neighbourhood,object,1653,8.25,44,"[Oud-West, De Pijp]"
39,neighbourhood_cleansed,object,0,0.00,22,"[De Baarsjes - Oud-West, De Pijp - Rivierenbuurt]"
40,neighbourhood_group_cleansed,float64,20030,100.00,0,[]
41,city,object,4,0.02,30,"[Amsterdam, Amsterdam-Zuidoost]"
42,state,object,127,0.63,55,"[Noord-Holland, North Holland]"
43,zipcode,object,866,4.32,6870,"[1054, 1055]"
44,market,object,42,0.21,4,"[Amsterdam, Other (International)]"
45,smart_location,object,0,0.00,31,"[Amsterdam, Netherlands, Amsterdam-Zuidoost, N..."
46,country_code,object,0,0.00,1,[NL]
47,country,object,0,0.00,1,[Netherlands]
48,latitude,float64,0,0.00,20030,"[52.36849906096132, 52.36515095638898]"
49,longitude,float64,0,0.00,20030,"[4.872006988802463, 4.872997700497941]"
50,is_location_exact,object,0,0.00,2,"[t, f]"
51,property_type,object,0,0.00,31,"[Apartment, House]"
52,room_type,object,0,0.00,3,"[Entire home/apt, Private room]"
53,accommodates,int64,0,0.00,15,"[2, 4]"
54,bathrooms,float64,10,0.05,17,"[1.0, 1.5]"
55,bedrooms,float64,8,0.04,13,"[1.0, 2.0]"
56,beds,float64,7,0.03,22,"[1.0, 2.0]"
57,bed_type,object,0,0.00,5,"[Real Bed, Pull-out Sofa]"
58,amenities,object,0,0.00,19034,"[{""translation missing: en.hosting_amenity_49""..."
59,square_feet,float64,19624,97.97,78,"[0.0, 753.0]"
60,price,object,0,0.00,429,"[$150.00, $100.00]"
61,weekly_price,object,17187,85.81,368,"[$600.00, $700.00]"
62,monthly_price,object,18469,92.21,328,"[$2,500.00, $2,000.00]"
63,security_deposit,object,6166,30.78,149,"[$0.00, $100.00]"
64,cleaning_fee,object,3629,18.12,101,"[$50.00, $30.00]"
65,guests_included,int64,0,0.00,13,"[1, 2]"
66,extra_people,object,0,0.00,103,"[$0.00, $25.00]"
67,minimum_nights,int64,0,0.00,51,"[2, 3]"
68,maximum_nights,int64,0,0.00,141,"[1125, 30]"
69,calendar_updated,object,0,0.00,68,"[today, a week ago]"
70,has_availability,object,0,0.00,1,[t]
71,availability_30,int64,0,0.00,31,"[0, 4]"
72,availability_60,int64,0,0.00,61,"[0, 3]"
73,availability_90,int64,0,0.00,91,"[0, 5]"
74,availability_365,int64,0,0.00,366,"[0, 5]"
75,calendar_last_scraped,object,0,0.00,2,"[2018-12-06, 2018-12-07]"
76,number_of_reviews,int64,0,0.00,354,"[0, 1]"
77,first_review,object,2406,12.01,2079,"[2016-03-30, 2017-04-17]"
78,last_review,object,2406,12.01,1202,"[2018-12-02, 2018-11-18]"
79,review_scores_rating,float64,2639,13.18,46,"[100.0, 98.0]"
80,review_scores_accuracy,float64,2649,13.23,9,"[10.0, 9.0]"
81,review_scores_cleanliness,float64,2647,13.22,9,"[10.0, 9.0]"
82,review_scores_checkin,float64,2661,13.29,8,"[10.0, 9.0]"
83,review_scores_communication,float64,2652,13.24,9,"[10.0, 9.0]"
84,review_scores_location,float64,2660,13.28,8,"[10.0, 9.0]"
85,review_scores_value,float64,2659,13.28,9,"[9.0, 10.0]"
86,requires_license,object,0,0.00,1,[f]
87,license,object,20021,99.96,2,"[0036.48.047.B.43, NL825517485B01]"
88,jurisdiction_names,object,672,3.35,1,[{Amsterdam}]
89,instant_bookable,object,0,0.00,2,"[f, t]"
90,is_business_travel_ready,object,0,0.00,1,[f]
91,cancellation_policy,object,0,0.00,4,"[strict_14_with_grace_period, moderate]"
92,require_guest_profile_picture,object,0,0.00,2,"[f, t]"
93,require_guest_phone_verification,object,0,0.00,2,"[f, t]"
94,calculated_host_listings_count,int64,0,0.00,27,"[1, 2]"
95,reviews_per_month,float64,2406,12.01,754,"[0.03, 0.07]"

In [5]:
listdata = []
listfeat=list(reviews.columns)
for item in listfeat:
    list1=[]
    list1.append(item)
    list1.append(str(reviews[item].dtype))
    list1.append(reviews[item].isna().sum())
    list1.append(round((reviews[item].isna().sum()/len(reviews))*100,2))
    list1.append(reviews[item].nunique())
    list1.append(list(reviews[item].value_counts().head(2).index))
    listdata.append(list1)

df_desc=pd.DataFrame(listdata,columns='dataFeatures dataType null nullPct unique uniqueSample'.split(' '))
df_desc

,dataFeatures,dataType,null,nullPct,unique,uniqueSample
0,listing_id,int64,0,0.00,17624,"[82482, 1469096]"
1,id,int64,0,0.00,431830,"[111155197, 106821906]"
2,date,object,0,0.00,2874,"[2017-05-28, 2018-04-02]"
3,reviewer_id,int64,0,0.00,411813,"[12574897, 44092711]"
4,reviewer_name,object,0,0.00,54244,"[David, Michael]"
5,comments,object,530,0.12,419933,[The host canceled this reservation 2 days bef...

In [6]:
listing=listing[listing.number_of_reviews>0]

In [7]:
listing.iloc[10]

id                                                                              42970
listing_url                                        https://www.airbnb.com/rooms/42970
scrape_id                                                              20181206172549
last_scraped                                                               2018-12-06
name                                      Comfortable room@PERFECT location + 2 bikes
summary                             A home away from home Great location Including...
space                               What I offer: great location, comfortable bed,...
description                         A home away from home Great location Including...
experiences_offered                                                              none
neighborhood_overview               My home is in the best neighborhood. Everythin...
notes                                                                             NaN
transit                             It is pretty easy to rent a bike as every Dutc...
access                              You have your own room with everything you nee...
interaction                         I live in the same building, so normally I am ...
house_rules                         Please do not smoke and I love pets, but for h...
thumbnail_url                                                                     NaN
medium_url                                                                        NaN
picture_url                         https://a0.muscache.com/im/pictures/53339208/2...
xl_picture_url                                                                    NaN
host_id                                                                        187580
host_url                                     https://www.airbnb.com/users/show/187580
host_name                                                                       Micha
host_since                                                                 2010-08-01
host_location                               Amsterdam, Noord-Holland, The Netherlands
host_about                          Hi!\r\n\r\nI am Micha. I am running my place, ...
host_response_time                                                     within an hour
host_response_rate                                                               100%
host_acceptance_rate                                                              NaN
host_is_superhost                                                                   t
host_thumbnail_url                  https://a0.muscache.com/im/pictures/user/d19cb...
host_picture_url                    https://a0.muscache.com/im/pictures/user/d19cb...
host_neighbourhood                                                     Grachtengordel
host_listings_count                                                                 2
host_total_listings_count                                                           2
host_verifications                             ['email', 'phone', 'reviews', 'jumio']
host_has_profile_pic                                                                t
host_identity_verified                                                              f
street                                          Amsterdam, North Holland, Netherlands
neighbourhood                                                       Amsterdam Centrum
neighbourhood_cleansed                                                   Centrum-West
neighbourhood_group_cleansed                                                      NaN
city                                                                        Amsterdam
state                                                                   North Holland
zipcode                                                                          1012
market                                                                      Amsterdam
smart_location                                                 Amsterdam, Netherlands
country_code                                                                       NL
country                                                                   Netherlands
latitude                                                                      52.3678
longitude                                                                     4.89001
is_location_exact                                                                   t
property_type                                                       Bed and breakfast
room_type                                                                Private room
accommodates                                                                        2
bathrooms                                                                           1
bedrooms                                                                            1
beds                                                                                1
bed_type                                                                     Real Bed
amenities                           {TV,"Cable TV",Internet,Wifi,Heating,"Family/k...
square_feet                                                                       NaN
price                                                                         $159.00
weekly_price                                                                      NaN
monthly_price                                                               $3,000.00
security_deposit                                                              $300.00
cleaning_fee                                                                   $35.00
guests_included                                                                     1
extra_people                                                                    $0.00
minimum_nights                                                                      3
maximum_nights                                                                   1100
calendar_updated                                                                today
has_availability                                                                    t
availability_30                                                                    14
availability_60                                                                    33
availability_90                                                                    63
availability_365                                                                   89
calendar_last_scraped                                                      2018-12-06
number_of_reviews                                                                 426
first_review                                                               2010-09-06
last_review                                                                2018-11-24
review_scores_rating                                                               98
review_scores_accuracy                                                             10
review_scores_cleanliness                                                          10
review_scores_checkin                                                              10
review_scores_communication                                                        10
review_scores_location                                                             10
review_scores_value                                                                 9
requires_license                                                                    f
license                                                                           NaN
jurisdiction_names                                                        {Amsterdam}
instant_bookable                                                                    t
is_business_travel_ready                                                            f
cancellation_policy                                       strict_14_with_grace_period
require_guest_profile_picture                                                       f
require_guest_phone_verification                                                    t
calculated_host_listings_count                                                      2
reviews_per_month                                                                4.24
Name: 10, dtype: object

In [8]:
new_listing=listing[['id','name','listing_url','summary','space','description','host_id','host_name','picture_url','neighbourhood_cleansed','latitude','longitude','property_type','room_type','accommodates','amenities','price','number_of_reviews','review_scores_rating','review_scores_cleanliness','review_scores_location','review_scores_checkin','review_scores_accuracy','review_scores_communication','review_scores_value']]

In [9]:
def removedollar(price):
    if ',' in str(price) :
        str_price = str(price).replace(",", "")
        return str_price.split('.')[0][1:]
    else :
        return str(price).split('.')[0][1:]
new_listing['price'] = pd.to_numeric(new_listing['price'].apply(removedollar))

In [10]:
new_listing.dropna(inplace=True)
new_listing['listing_id']=new_listing['id']
new_listing.drop(['id'], axis=1,inplace=True)
new_listing.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12750 entries, 0 to 20007
Data columns (total 25 columns):
name                           12750 non-null object
listing_url                    12750 non-null object
summary                        12750 non-null object
space                          12750 non-null object
description                    12750 non-null object
host_id                        12750 non-null int64
host_name                      12750 non-null object
picture_url                    12750 non-null object
neighbourhood_cleansed         12750 non-null object
latitude                       12750 non-null float64
longitude                      12750 non-null float64
property_type                  12750 non-null object
room_type                      12750 non-null object
accommodates                   12750 non-null int64
amenities                      12750 non-null object
price                          12750 non-null int64
number_of_reviews              12750 non-null int64
review_scores_rating           12750 non-null float64
review_scores_cleanliness      12750 non-null float64
review_scores_location         12750 non-null float64
review_scores_checkin          12750 non-null float64
review_scores_accuracy         12750 non-null float64
review_scores_communication    12750 non-null float64
review_scores_value            12750 non-null float64
listing_id                     12750 non-null int64
dtypes: float64(9), int64(5), object(11)
memory usage: 2.5+ MB

In [11]:
new_listing=new_listing.reset_index(drop=True)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re
def clean_text(x):
    letter = re.sub("[^a-zA-Z1-9]","_",x)
    return ' '.join(letter.split()).lower()

def new_amenties(x):
    fasilitas = str(x)[1:-1].split(',')
    fas=[]
    for item in fasilitas:
        name = clean_text(item)
        if 'missing' not in name :
            fas.append(name)
    return ' '.join(fas)
new_listing['amenities']=new_listing['amenities'].apply(new_amenties)

In [13]:
cv_res = CountVectorizer()
cv_res_hotel = cv_res.fit_transform(new_listing['amenities'])
cos_sim = cosine_similarity(cv_res_hotel)

In [14]:
df_sim=pd.DataFrame(cos_sim,index=new_listing.index,columns=new_listing.listing_id)
df_sim['loc'] = new_listing['neighbourhood_cleansed']

In [15]:
def removelistingid(x):
    if x in df_sim.columns:
        return x
    else :
        return np.nan
reviews['listing_id']=reviews['listing_id'].apply(removelistingid)
reviews.dropna(inplace=True)
reviews=reviews.sort_values(by='date',ascending=False)
list_id=[]
for item in list(reviews.listing_id.value_counts().head(300).index):
    if item in df_sim.columns:
        list_id.append(item)
len(list_id)
df_sim1=df_sim[list_id]
df_sim1['loc'] = new_listing['neighbourhood_cleansed']
df_sim1['loc']
df_sim1.shape

(12750, 301)

In [16]:
def get_recom_hotel(id_rev,loc):
#     reviews = pd.read_csv('clean_reviews.csv')
#     df_sim1 = pd.read_csv('cleansim.csv')
#     new_listing = pd.read_csv('clean_listing.csv')
#     print(df_sim1.shape)
#     print(new_listing.shape)
    index_similar=df_sim1[df_sim1['loc']==loc][(int(reviews[reviews.reviewer_id==id_rev].listing_id.iloc[0]))].sort_values(ascending=False).head(11).index
#     print(index_similar)
    return new_listing.loc[index_similar][1:]
get_recom_hotel(10952,'De Baarsjes - Oud-West')

,name,listing_url,summary,space,description,host_id,host_name,picture_url,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,amenities,price,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_location,review_scores_checkin,review_scores_accuracy,review_scores_communication,review_scores_value,listing_id
12546,CENTRE Apartment NEAR MUSEUM DISTRICT,https://www.airbnb.com/rooms/29046160,"In the city centre, near Leidseplein and very ...",The kitchenette is fully furnished with micro...,"In the city centre, near Leidseplein and very ...",389623,Ric,https://a0.muscache.com/im/pictures/6005b520-d...,De Baarsjes - Oud-West,52.364592,4.873899,Apartment,Private room,2,tv _cable_tv_ internet wifi kitchen _paid_park...,159,5,100.0,10.0,10.0,10.0,10.0,10.0,10.0,29046160
10815,Typical A’dam-style apartment with lovely garden,https://www.airbnb.com/rooms/23444097,Spacious apartment in the upcoming and lively ...,"Modern, spacious apartment. Big living room an...",Spacious apartment in the upcoming and lively ...,10474724,Anne,https://a0.muscache.com/im/pictures/c69ba5d0-9...,De Baarsjes - Oud-West,52.370893,4.849455,Apartment,Entire home/apt,2,tv wifi kitchen _paid_parking_off_premises_ he...,85,2,100.0,10.0,10.0,10.0,10.0,10.0,10.0,23444097
425,The Best 2-Floor CANAL Apartment!,https://www.airbnb.com/rooms/817058,Have Amsterdam right at your feet and watch th...,This apartment is brand new and spacious (130 ...,Have Amsterdam right at your feet and watch th...,4291496,Niels & Sofia,https://a0.muscache.com/im/pictures/e182272a-5...,De Baarsjes - Oud-West,52.364965,4.859915,Condominium,Entire home/apt,4,tv _cable_tv_ internet wifi _wheelchair_access...,190,32,97.0,10.0,9.0,10.0,10.0,10.0,9.0,817058
2171,Romantic app. Vondelpark with bikes,https://www.airbnb.com/rooms/4339481,"This is a sweet, romantic apartment on the sec...",If the sun shines there's always a side of the...,"This is a sweet, romantic apartment on the sec...",3157950,Annoek,https://a0.muscache.com/im/pictures/54776201/d...,De Baarsjes - Oud-West,52.358078,4.858964,Apartment,Entire home/apt,2,internet wifi kitchen _paid_parking_off_premis...,110,24,99.0,10.0,10.0,10.0,10.0,10.0,10.0,4339481
2403,Quaint Outhouse in Amsterdam West ( pvt bathr...,https://www.airbnb.com/rooms/4887616,This ground floor apartment in Amsterdam West ...,The quaint bedroom comes with a four-poster be...,This ground floor apartment in Amsterdam West ...,25142874,Varun,https://a0.muscache.com/im/pictures/4b545bf8-8...,De Baarsjes - Oud-West,52.361876,4.851574,Apartment,Private room,2,internet _pets_live_on_this_property_ dog_s_ h...,80,118,94.0,10.0,9.0,10.0,10.0,10.0,9.0,4887616
7389,Beautiful City Centre Garden independent Room,https://www.airbnb.com/rooms/16142970,You will be hosted in our beautiful independen...,You will share the entrance of the house and t...,You will be hosted in our beautiful independen...,5785909,Alvaro And Adrie,https://a0.muscache.com/im/pictures/7d296ae4-e...,De Baarsjes - Oud-West,52.369605,4.874888,Apartment,Private room,2,tv _cable_tv_ wifi kitchen heating washer drye...,140,2,100.0,10.0,10.0,10.0,10.0,10.0,10.0,16142970
8817,Hidden gem with garden in city centre,https://www.airbnb.com/rooms/19145903,Great apartment with lush garden. Very suitabl...,The master bedroom boasts a large king sized b...,Great apartment with lush garden. Very suitabl...,6810286,Guy,https://a0.muscache.com/im/pictures/6eaae5be-a...,De Baarsjes - Oud-West,52.370938,4.866825,Apartment,Entire home/apt,2,wifi kitchen _pets_allowed_ _hot_tub_ heating ...,199,8,98.0,10.0,10.0,9.0,10.0,10.0,9.0,19145903
4701,Unique centrally located apartment,https://www.airbnb.com/rooms/10095391,With only 2 minutes walking distance from the ...,Being a former shop that was around for more t...,With only 2 minutes walking distance from the ...,20804343,Bas,https://a0.muscache.com/im/pictures/6459c6b1-c...,De Baarsjes - Oud-West,52.365624,4.878030,Apartment,Entire home/apt,3,tv _cable_tv_ internet wifi _wheelchair_access...,195,4,100.0,10.0,10.0,10.0,10.0,10.0,10.0,10095391
3549,3 room apart. with lovely garden near Vondelpark,https://www.airbnb.com/rooms/7379564,"The apartment with private entrance, located i...","Welcome to my apartment, feel at home and enjo...","The apartment with private entrance, located i...",758308,Kutay,https://a0.muscache.com/im/pictures/b68706e7-8...,De Baarsjes - Oud-West,52.359398,4.851069,Apartment,Entire home/apt,4,tv _cable_tv_ internet wifi kitchen _paid_park...,200,10,96.0,10.0,9.0,10.0,10.0,10.0,9.0,7379564
9447,"CENTRAL Design private Apartment, walk everywh...",https://www.airbnb.com/rooms/20225909,This ground floor gorgeous apartment with ensu...,This Wonderfully Decorated Deluxe Apartment wi...,This ground floor gorgeous apartment with ensu...,71257610,Mandy,https://a0.muscache.com/im/pictures/380bf00f-8...,De Baarsjes - Oud-West,52.361885,4.864629,Townhouse,Entire home/apt,2,tv _cable_tv_ wifi kitchen heating washer _smo...,119,10,100.0,10.0,10.0,10.0,10.0,10.0,10.0,20225909

In [17]:
reviews[reviews['reviewer_name']=='Lam'].sort_values('date')
reviews[reviews['reviewer_name']=='Lam'].sort_values(by='date',ascending=False)

def removelistingid1(x):
    if x in df_sim1.columns:
        return x
    else :
        return np.nan
print(reviews.shape)
reviews['listing_id']=reviews['listing_id'].apply(removelistingid1)
reviews.dropna(inplace=True)
reviews=reviews.sort_values(by='date',ascending=False)
reviews.reviewer_id.value_counts()
print(reviews.shape)
reviews.reviewer_id.value_counts().head(10)

(354790, 6)
(82502, 6)

18024656    6
52093112    6
31635589    4
1846693     4
3281343     4
14619699    4
825755      4
5942510     4
8526157     4
56232374    4
Name: reviewer_id, dtype: int64

In [18]:
reviews.head(10)

,listing_id,id,date,reviewer_id,reviewer_name,comments
114561,2763386.0,355928444,2018-12-06,27370265,Dante,Rick is a fantastic host! His apartment room i...
35089,654931.0,355925574,2018-12-06,130719768,Josh,Had a great two night stay wish we could have ...
235846,9146453.0,355891140,2018-12-06,22463674,Peter,Akko’s place is the best spot possible in Amst...
162252,4934237.0,355915817,2018-12-06,32507569,Cranston,Great space. Easy communication. Would definit...
135907,3763895.0,355717840,2018-12-05,191696819,Laila,The host was very nice and kind and she will h...
1726,29051.0,355704327,2018-12-05,117261720,Jonas,Edwin is a really cool host with a really well...
37354,690757.0,355713991,2018-12-05,166848795,Leslie,Buena ubicación pero al cuarto le hace falta i...
259503,11178401.0,355512015,2018-12-04,79566639,Anna,"Said was communicative, set clear expectations..."
206085,7276869.0,355484481,2018-12-04,32575647,Allen,The place was in a great location walking dist...
203910,7190115.0,355475562,2018-12-04,130417375,Wilson,Wonderful service great location and very frie...

df_sim1[reviews[reviews.reviewer_id==10952].listing_id[0]]
listing[listing.id==82482]
def recom(REV_ID):
    reviews = pd.read_csv('clean_reviews.csv')
    data_login=reviews[reviews['reviewer_id']==REV_ID]
    return data_login
recom(10952).reviewer_name.iloc[0]
reviews[reviews.reviewer_id==12574897]
reviews[reviews.listing_id==82482]

new_listing.to_csv('clean_listing.csv',index=False)
reviews.to_csv('clean_reviews.csv',index=False)
df_sim1.to_csv('cleansim.csv',index=False)