recomended system
1. simple recomended
2. content based recomended
3. colleberation filtering recomended

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# DEMOGRAPHIC FILTERINGS

In [2]:
meta = pd.read_csv('the-movies-dataset/movies_metadata.csv',low_memory=False)

In [3]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45466 non-null object
belongs_to_collection    4494 non-null object
budget                   45466 non-null object
genres                   45466 non-null object
homepage                 7782 non-null object
id                       45466 non-null object
imdb_id                  45449 non-null object
original_language        45455 non-null object
original_title           45466 non-null object
overview                 44512 non-null object
popularity               45461 non-null object
poster_path              45080 non-null object
production_companies     45463 non-null object
production_countries     45463 non-null object
release_date             45379 non-null object
revenue                  45460 non-null float64
runtime                  45203 non-null float64
spoken_languages         45460 non-null object
status                   45379 non-null object
tagline                  20412 non-null object
title                    45460 non-null object
video                    45460 non-null object
vote_average             45460 non-null float64
vote_count               45460 non-null float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

## SIMPLE RECOMENDED

In [4]:
vote_data=meta[['original_title','vote_average','vote_count']]

In [5]:
vote_data['vote_average'].mean()

5.618207215133889

In [6]:
def weight_rating(row):
    v=row['vote_count'] # v is the number of votes for the movie
    m=1500 # minimal vote count yang ingin di tampilkan di chat 'm is the minimum votes required to be listed in the chart
    r=row['vote_average'] #R is the average rating of the movie
    c=5.6 # mean vote_average C is the mean vote across the whole report
    wr=((v/(v+m)*r)+(m/(v+m)*c))
    return wr

In [7]:
vote_data['score'] = vote_data.apply(weight_rating,axis=1)
vote_data

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                          original_title  vote_average  vote_count     score
0                              Toy Story           7.7      5415.0  7.244469
1                                Jumanji           6.9      2413.0  6.401661
2                       Grumpier Old Men           6.5        92.0  5.652010
3                      Waiting to Exhale           6.1        34.0  5.611082
4            Father of the Bride Part II           5.7       173.0  5.610341
5                                   Heat           7.7      1886.0  6.769699
6                                Sabrina           6.2       141.0  5.651554
7                           Tom and Huck           5.4        45.0  5.594175
8                           Sudden Death           5.5       174.0  5.589606
9                              GoldenEye           6.6      1194.0  6.043207
10                The American President           6.5       199.0  5.705415
11           Dracula: Dead and Loving It           5.7       210.0  5.612281
12                                 Balto           7.1       423.0  5.929953
13                                 Nixon           7.1        72.0  5.668702
14                      Cutthroat Island           5.7       137.0  5.608369
15                                Casino           7.8      1343.0  6.639254
16                 Sense and Sensibility           7.2       364.0  5.912446
17                            Four Rooms           6.5       539.0  5.837911
18        Ace Ventura: When Nature Calls           6.1      1128.0  5.814612
19                           Money Train           5.4       224.0  5.574014
20                            Get Shorty           6.4       305.0  5.735180
21                               Copycat           6.5       199.0  5.705415
22                             Assassins           6.0       394.0  5.683210
23                                Powder           6.3       143.0  5.660925
24                     Leaving Las Vegas           7.1       365.0  5.893566
25                               Othello           7.0        33.0  5.630137
26                          Now and Then           6.6        91.0  5.657197
27                            Persuasion           7.4        36.0  5.642188
28            La Cité des Enfants Perdus           7.6       308.0  5.940708
29                             摇啊摇，摇到外婆桥           6.5        17.0  5.610086
...                                  ...           ...         ...       ...
45436                    The Final Storm           3.7        11.0  5.586168
45437                     In a Heartbeat           8.3       146.0  5.839490
45438             Bloed, Zweet en Tranen           6.8        11.0  5.608736
45439                       Jungle Woman           5.8         2.0  5.600266
45440                  To Be Fat Like Me           5.0        12.0  5.595238
45441                        Cadet Kelly           5.2       145.0  5.564742
45442               Le tripot clandestin           5.0         3.0  5.598802
45443    L'Homme à la tête de caoutchouc           7.6        29.0  5.637933
45444                Les cartes vivantes           6.1         8.0  5.602653
45445           Les affiches en goguette           4.5         2.0  5.598535
45446            Le locataire diabolique           6.7        12.0  5.608730
45447               Le Roi du maquillage           6.0         6.0  5.601594
45448  Les Transmutations imperceptibles           5.0         2.0  5.599201
45449   Pooh's Heffalump Halloween Movie           5.4         7.0  5.599071
45450                  L'Homme orchestre           6.5        22.0  5.613009
45451     Nouvelles luttes extravagantes           6.5         6.0  5.603586
45452                        Deep Hearts           0.0         0.0  5.600000
45453                                Maa           6.6        14.0  5.609247
45454                  The Morning After           4.0         2.0  5.597870
45455         San Michele aveva un gallo           6.0         3.0  5.600798
45456                   House of Horrors           6.3         8.0  5.603714
45457          Shadow of the Blair Witch           7.0         2.0  5.601864
45458                The Burkittsville 7           7.0         1.0  5.600933
45459                    Caged Heat 3000           3.5         1.0  5.598601
45460                         Robin Hood           5.7        26.0  5.601704
45461                            رگ خواب           4.0         1.0  5.598934
45462                Siglo ng Pagluluwal           9.0         3.0  5.606786
45463                           Betrayal           3.8         6.0  5.592829
45464                Satana likuyushchiy           0.0         0.0  5.600000
45465                           Queerama           0.0         0.0  5.600000

[45466 rows x 4 columns]

In [8]:
vote_data.sort_values(by='score',ascending=False)

,original_title,vote_average,vote_count,score
314,The Shawshank Redemption,8.5,8358.0,8.058734
12481,The Dark Knight,8.3,12269.0,8.005861
2843,Fight Club,8.3,9678.0,7.937681
834,The Godfather,8.5,6024.0,7.921850
292,Pulp Fiction,8.3,8670.0,7.901770
15480,Inception,8.1,14075.0,7.859230
22879,Interstellar,8.1,11187.0,7.804422
351,Forrest Gump,8.2,8147.0,7.795729
7000,The Lord of the Rings: The Return of the King,8.1,8226.0,7.714436
1154,The Empire Strikes Back,8.2,5998.0,7.679861
4863,The Lord of the Rings: The Fellowship of the Ring,8.0,8892.0,7.653580
256,Star Wars,8.1,6778.0,7.646992
18465,Intouchables,8.2,5410.0,7.635601
522,Schindler's List,8.3,4436.0,7.617722
23673,Whiplash,8.3,4376.0,7.610756
5814,The Lord of the Rings: The Two Towers,8.0,7641.0,7.606170
23753,Guardians of the Galaxy,7.9,10014.0,7.600365
46,Se7en,8.1,5915.0,7.594268
2458,The Matrix,7.9,9079.0,7.573882
5481,千と千尋の神隠し,8.3,3968.0,7.559327
1225,Back to the Future,8.0,6239.0,7.534824
289,Léon,8.2,4293.0,7.526774
20051,Django Unchained,7.8,10297.0,7.520268
24860,The Imitation Game,8.0,5895.0,7.513185
2211,La vita è bella,8.3,3643.0,7.512522
3030,The Green Mile,8.2,4166.0,7.511684
359,The Lion King,8.0,5520.0,7.487179
22131,The Wolf of Wall Street,7.9,6768.0,7.482729
30315,Inside Out,7.9,6737.0,7.481158
586,The Silence of the Lambs,8.1,4549.0,7.480063
...,...,...,...,...
17272,Green Lantern,5.1,2551.0,5.285139
35220,Zoolander 2,4.7,814.0,5.283405
23110,The Legend of Hercules,4.4,542.0,5.281489
42096,Rings,4.8,1075.0,5.266019
1486,Speed 2: Cruise Control,4.1,439.0,5.260392
20791,Scary Movie 5,4.6,813.0,5.248508
12358,Meet the Spartans,3.8,370.0,5.243850
12911,Disaster Movie,3.1,250.0,5.242857
9710,Son of the Mask,3.6,346.0,5.225135
21018,After Earth,5.0,2579.0,5.220642
3471,Battlefield Earth,3.0,259.0,5.217169
20314,Movie 43,4.5,816.0,5.212435
18609,Ghost Rider: Spirit of Vengeance,4.7,1163.0,5.206947
15422,The Last Airbender,4.7,1180.0,5.203731
24413,Left Behind,3.7,396.0,5.203165
11557,Epic Movie,3.2,334.0,5.162923
21238,Sharknado,3.8,484.0,5.160887
30556,Independence Day: Resurgence,4.9,2550.0,5.159259
18101,Jack and Jill,4.0,619.0,5.132610
7939,Catwoman,4.2,833.0,5.100129
28207,The Boy Next Door,4.1,1034.0,4.987924
13566,Dragonball Evolution,2.9,475.0,4.950633
1491,Batman & Robin,4.2,1447.0,4.912589
26563,Fantastic Four,4.4,2322.0,4.870958
19729,Midnight Man,NaN,NaN,NaN
19730,"[{'iso_639_1': 'en', 'name': 'English'}]",NaN,NaN,NaN
29502,マルドゥック・スクランブル 排気,NaN,NaN,NaN
29503,"[{'iso_639_1': 'ja', 'name': '日本語'}]",NaN,NaN,NaN
35586,Avalanche Sharks,NaN,NaN,NaN
35587,"[{'iso_639_1': 'en', 'name': 'English'}]",NaN,NaN,NaN

In [9]:
vote_data.sort_values(by='vote_count',ascending=False)

,original_title,vote_average,vote_count,score
15480,Inception,8.1,14075.0,7.859230
12481,The Dark Knight,8.3,12269.0,8.005861
14551,Avatar,7.2,12114.0,7.023711
17818,The Avengers,7.4,12000.0,7.200000
26564,Deadpool,7.4,11444.0,7.191409
22879,Interstellar,8.1,11187.0,7.804422
20051,Django Unchained,7.8,10297.0,7.520268
23753,Guardians of the Galaxy,7.9,10014.0,7.600365
2843,Fight Club,8.3,9678.0,7.937681
18244,The Hunger Games,6.9,9634.0,6.724861
26553,Mad Max: Fury Road,7.3,9629.0,7.070869
18252,The Dark Knight Rises,7.6,9263.0,7.321267
2458,The Matrix,7.9,9079.0,7.573882
12588,Iron Man,7.4,8951.0,7.141652
20830,Iron Man 3,6.8,8951.0,6.627768
4863,The Lord of the Rings: The Fellowship of the Ring,8.0,8892.0,7.653580
25084,Jurassic World,6.5,8842.0,6.369464
292,Pulp Fiction,8.3,8670.0,7.901770
19971,The Hobbit: An Unexpected Journey,7.0,8427.0,6.788456
314,The Shawshank Redemption,8.5,8358.0,8.058734
7000,The Lord of the Rings: The Return of the King,8.1,8226.0,7.714436
351,Forrest Gump,8.2,8147.0,7.795729
26555,Star Wars: The Force Awakens,7.5,7993.0,7.199779
1639,Titanic,7.5,7770.0,7.192557
19261,Skyfall,6.9,7718.0,6.688457
30543,Suicide Squad,5.9,7717.0,5.851177
5814,The Lord of the Rings: The Two Towers,8.0,7641.0,7.606170
10122,Batman Begins,7.5,7511.0,7.183720
26567,Captain America: Civil War,7.1,7462.0,6.848940
30051,The Martian,7.6,7442.0,7.264505
...,...,...,...,...
42720,Brian Gaar: Jokes I Wrote At Work,0.0,0.0,5.600000
42721,Andy Peters: Exclamation Mark Question Point,0.0,0.0,5.600000
42722,Barry Hilton: The Live Series,0.0,0.0,5.600000
42723,Keith Robinson: Back of the Bus Funny,0.0,0.0,5.600000
42724,Ralphie May: Unruly,0.0,0.0,5.600000
38353,Cheerleader,0.0,0.0,5.600000
42726,Jay Mohr: Happy. And A Lot.,0.0,0.0,5.600000
38352,ＳＭガールズ セイバーマリオネットＲ,0.0,0.0,5.600000
42729,Mick Foley: Cheap Pops,0.0,0.0,5.600000
38347,Galerions Rion,0.0,0.0,5.600000
38343,教科書にないッ！,0.0,0.0,5.600000
42734,Susan Calman: Lady Like,0.0,0.0,5.600000
42736,Bridget Everett: Gynecological Wonder,0.0,0.0,5.600000
29842,Der Schatz,0.0,0.0,5.600000
32988,Con la rabbia agli occhi,0.0,0.0,5.600000
42742,Margaret Cho: PsyCHO,0.0,0.0,5.600000
32991,Joko invoca Dio... e muori,0.0,0.0,5.600000
42745,Jimmy Dore: Sentenced To Live,0.0,0.0,5.600000
38331,Tokusô sensha-tai Dominion,0.0,0.0,5.600000
42747,Sarah Colonna: I Can't Feel My Legs,0.0,0.0,5.600000
42748,Miles Jupp: Is The Chap You're Thinking Of,0.0,0.0,5.600000
38327,Sin: The Movie,0.0,0.0,5.600000
38326,Sentou Yousei Yukikaze,0.0,0.0,5.600000
45465,Queerama,0.0,0.0,5.600000
19729,Midnight Man,NaN,NaN,NaN
19730,"[{'iso_639_1': 'en', 'name': 'English'}]",NaN,NaN,NaN
29502,マルドゥック・スクランブル 排気,NaN,NaN,NaN
29503,"[{'iso_639_1': 'ja', 'name': '日本語'}]",NaN,NaN,NaN
35586,Avalanche Sharks,NaN,NaN,NaN
35587,"[{'iso_639_1': 'en', 'name': 'English'}]",NaN,NaN,NaN

## Content Based

> Based on genres

In [10]:
from ast import literal_eval

>> convert string to list

In [11]:
literal_eval(meta['genres'].iloc[0])

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [12]:
content_based_genres=meta[meta['vote_count']>300][['original_title','genres']]
content_based_genres.reset_index(drop=True,inplace=True)

In [13]:
def newgenres(x):
    genres=[]
    x=literal_eval(x)
    for item in x:
        genres.append(item['name'])
    return ' '.join(genres)

In [14]:
content_based_genres['newgenres']=content_based_genres['genres'].apply(newgenres)

In [15]:
content_based_genres

,original_title,genres,newgenres
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family
2,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller
3,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller
4,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",Family Animation Adventure
5,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime
6,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance
7,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy
8,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Adventure
9,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",Comedy Thriller Crime
10,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Crime Thriller
11,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance
12,La Cité des Enfants Perdus,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",Fantasy Science Fiction Adventure
13,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller Mystery
14,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",Fantasy Drama Comedy Family
15,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]",Drama
16,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance
17,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",Action Fantasy
18,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",Crime Mystery Thriller
19,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Drama Family
20,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller
21,Friday,"[{'id': 35, 'name': 'Comedy'}]",Comedy
22,From Dusk Till Dawn,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",Horror Action Thriller Crime
23,Broken Arrow,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Thriller
24,La Haine,"[{'id': 18, 'name': 'Drama'}]",Drama
25,Happy Gilmore,"[{'id': 35, 'name': 'Comedy'}]",Comedy
26,The Bridges of Madison County,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance
27,Braveheart,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History War
28,Taxi Driver,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",Crime Drama
29,The Birdcage,"[{'id': 35, 'name': 'Comedy'}]",Comedy
...,...,...,...
3002,Power Rangers,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction
3003,Alien: Covenant,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",Horror Science Fiction Thriller
3004,Going in Style,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Drama
3005,Alibi.com,"[{'id': 35, 'name': 'Comedy'}]",Comedy
3006,Smurfs: The Lost Village,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Comedy Family
3007,The Discovery,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance Science Fiction Thriller
3008,Gifted,"[{'id': 18, 'name': 'Drama'}]",Drama
3009,Band of Brothers,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama War
3010,"Everything, Everything","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance
3011,Baywatch,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Action Comedy
3012,The Mummy,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Adventure
3013,The Fate of the Furious,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Thriller
3014,It Comes at Night,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",Horror Mystery Thriller
3015,Cars 3,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",Family Comedy Animation Adventure
3016,Boyka: Undisputed IV,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Crime
3017,Baby Driver,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime
3018,Okja,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",Adventure Drama Fantasy Science Fiction
3019,Rough Night,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",Drama Comedy
3020,Despicable Me 3,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",Action Animation Adventure Family Comedy
3021,War for the Planet of the Apes,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",Drama Science Fiction War
3022,Valerian and the City of a Thousand Planets,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",Adventure Science Fiction Action
3023,What Happened to Monday,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller
3024,Atomic Blonde,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Action Thriller
3025,Dunkirk,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History Thriller War
3026,Transformers: The Last Knight,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Thriller Adventure
3027,Tre uomini e una gamba,"[{'id': 35, 'name': 'Comedy'}]",Comedy
3028,The Dark Tower,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",Action Western Science Fiction Fantasy Horror
3029,The Emoji Movie,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",Comedy Family Animation
3030,Shot Caller,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller
3031,Girls Trip,"[{'id': 35, 'name': 'Comedy'}]",Comedy

>> convert to sparsematrix with countvectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
cv=CountVectorizer()
cv_genres_result = cv.fit_transform(content_based_genres['newgenres'])

In [18]:
cv_df=pd.DataFrame(cv_genres_result.todense(),columns=cv.get_feature_names(),index=content_based_genres['original_title'])

In [19]:
cv_df.head()

,action,adventure,animation,comedy,crime,documentary,drama,family,fantasy,fiction,...,horror,movie,music,mystery,romance,science,thriller,tv,war,western
original_title,,,,,,,,,,,,,,,,,,,,,
Toy Story,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Jumanji,0,1,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
Heat,1,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
GoldenEye,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Balto,0,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

# example cosine_similiarity

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
data_1 = 'wifi AC breakfast'
data_2 = 'wifi pool'
data_3 = 'breakfast AC'
data_4 = 'pool'
data_5 = 'bar pool wifi karoke'

In [22]:
datahotel=[data_1,data_2,data_3,data_4,data_5]
datahotel = pd.DataFrame(datahotel,columns=['fasilitas'],index=['hotel 1','hotel 2','hotel 3','hotel 4','hotel 5'])

In [23]:
cv_hotel=CountVectorizer()
cv_hotel_res=cv_hotel.fit_transform(datahotel['fasilitas'])

In [24]:
pd.DataFrame(cv_hotel_res.todense(),columns=cv_hotel.get_feature_names(),index=datahotel.index)

         ac  bar  breakfast  karoke  pool  wifi
hotel 1   1    0          1       0     0     1
hotel 2   0    0          0       0     1     1
hotel 3   1    0          1       0     0     0
hotel 4   0    0          0       0     1     0
hotel 5   0    1          0       1     1     1

In [25]:
con_sim_hotel = cosine_similarity(cv_hotel_res)

In [26]:
pd.DataFrame(con_sim_hotel,index=datahotel.index,columns=datahotel.index)

          hotel 1   hotel 2   hotel 3   hotel 4   hotel 5
hotel 1  1.000000  0.408248  0.816497  0.000000  0.288675
hotel 2  0.408248  1.000000  0.000000  0.707107  0.707107
hotel 3  0.816497  0.000000  1.000000  0.000000  0.000000
hotel 4  0.000000  0.707107  0.000000  1.000000  0.500000
hotel 5  0.288675  0.707107  0.000000  0.500000  1.000000

## cosine_similarity movie

In [27]:
con_sim_movie= cosine_similarity(cv_genres_result)

In [28]:
index_to_search=content_based_genres[content_based_genres['original_title']=='Jumanji'].index[0]
pd.Series(con_sim_movie[index_to_search],index=content_based_genres['original_title']).sort_values(ascending=False)

original_title
City of Ember                                                     1.000000
Harry Potter and the Deathly Hallows: Part 2                      1.000000
Harry Potter and the Goblet of Fire                               1.000000
Pete's Dragon                                                     1.000000
Harry Potter and the Philosopher's Stone                          1.000000
The Wizard of Oz                                                  1.000000
Pan                                                               1.000000
The Chronicles of Narnia: Prince Caspian                          1.000000
Labyrinth                                                         1.000000
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe    1.000000
Inkheart                                                          1.000000
Harry Potter and the Prisoner of Azkaban                          1.000000
Harry Potter and the Half-Blood Prince                            1.000000
Peter Pan                                                         1.000000
Fantastic Beasts and Where to Find Them                           1.000000
Percy Jackson & the Olympians: The Lightning Thief                1.000000
Harry Potter and the Chamber of Secrets                           1.000000
Oz: The Great and Powerful                                        1.000000
The Chronicles of Narnia: The Voyage of the Dawn Treader          1.000000
Alice in Wonderland                                               1.000000
The BFG                                                           1.000000
Percy Jackson: Sea of Monsters                                    1.000000
Harry Potter and the Deathly Hallows: Part 1                      1.000000
Jumanji                                                           1.000000
The Spiderwick Chronicles                                         1.000000
Stardust                                                          0.866025
Harry Potter and the Order of the Phoenix                         0.866025
The Rescuers                                                      0.866025
The Neverending Story                                             0.866025
Arthur 3: la guerre des deux mondes                               0.866025
                                                                    ...
Tropa de Elite                                                    0.000000
American Gangster                                                 0.000000
Shot Caller                                                       0.000000
Before the Devil Knows You're Dead                                0.000000
No Country for Old Men                                            0.000000
Be Kind Rewind                                                    0.000000
The Theory of Everything                                          0.000000
The Man from Earth                                                0.000000
Dumb and Dumber To                                                0.000000
Mr. Magorium's Wonder Emporium                                    0.000000
The Mist                                                          0.000000
Relatos salvajes                                                  0.000000
Hitman                                                            0.000000
I Am Legend                                                       0.000000
In Bruges                                                         0.000000
El orfanato                                                       0.000000
Juno                                                              0.000000
The Bucket List                                                   0.000000
The Kite Runner                                                   0.000000
Sweeney Todd: The Demon Barber of Fleet Street                    0.000000
There Will Be Blood                                               0.000000
Charlie Wilson's War                                              0.000000
P.S. I Love You                                                   0.000000
27 Dresses                                                        0.000000
[REC]                                                             0.000000
Cloverfield                                                       0.000000
Rambo                                                             0.000000
Meet the Spartans                                                 0.000000
Babysitting                                                       0.000000
Girls Trip                                                        0.000000
Length: 3032, dtype: float64

In [29]:
def get_recomendation_based_genres(title):
    index_to_search=content_based_genres[content_based_genres['original_title']==title].index[0]
    series_similiar=pd.Series(con_sim_movie[index_to_search])
    index_similiar = series_similiar.sort_values(ascending=False).head(10).index
    return content_based_genres.loc[index_similiar]

In [30]:
get_recomendation_based_genres('Iron Man')

,original_title,genres,newgenres
2508,Guardians of the Galaxy,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Adventure
2303,After Earth,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Action Adventure
2294,Star Trek Into Darkness,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction
2291,Iron Man 3,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction
2394,The Hunger Games: Catching Fire,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Science Fiction
140,Independence Day,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction
735,X-Men,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Science Fiction
2792,Hardcore Henry,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction
1998,Transformers: Dark of the Moon,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Adventure
2108,Journey 2: The Mysterious Island,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Science Fiction

## CONTENT BASED CAST

In [31]:
content_based_genres_cast_crew=meta[meta['vote_count']>300][['original_title','genres','id']]

In [32]:
content_based_genres_cast_crew.head()

   original_title                                             genres     id
0       Toy Story  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...    862
1         Jumanji  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   8844
5            Heat  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...    949
9       GoldenEye  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...    710
12          Balto  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...  21032

In [33]:
credits=pd.read_csv('the-movies-dataset/credits.csv')

In [34]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
cast    45476 non-null object
crew    45476 non-null object
id      45476 non-null int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [35]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
adult                    45466 non-null object
belongs_to_collection    4494 non-null object
budget                   45466 non-null object
genres                   45466 non-null object
homepage                 7782 non-null object
id                       45466 non-null object
imdb_id                  45449 non-null object
original_language        45455 non-null object
original_title           45466 non-null object
overview                 44512 non-null object
popularity               45461 non-null object
poster_path              45080 non-null object
production_companies     45463 non-null object
production_countries     45463 non-null object
release_date             45379 non-null object
revenue                  45460 non-null float64
runtime                  45203 non-null float64
spoken_languages         45460 non-null object
status                   45379 non-null object
tagline                  20412 non-null object
title                    45460 non-null object
video                    45460 non-null object
vote_average             45460 non-null float64
vote_count               45460 non-null float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [36]:
content_based_genres['id']=pd.to_numeric(meta[meta['vote_count']>300]['id']).reset_index(drop=True)

In [37]:
pd.to_numeric(meta[meta['vote_count']>300]['id'])

0           862
1          8844
5           949
9           710
12        21032
15          524
16         4584
17            5
18         9273
20         8012
22         9691
24          451
28          902
31           63
33         9598
35          687
38         9603
43         9312
46          807
47        10530
49          629
68        10634
69          755
93         9208
95          406
102        9614
103         688
108         197
109         103
139       11000
          ...
42901    305470
42902    126889
43059    353070
43061    398929
43156    137116
43157    376134
43186    400928
43190    331214
43220    417678
43231    339846
43238    282035
43255    337339
43289    418078
43294    260514
43301    348893
43644    339403
43645    387426
43691    397422
44009    324852
44274    281338
44337    339964
44624    406990
44632    341013
44678    374720
44842    335988
44949     38286
45014    353491
45139    378236
45174    339692
45204    417870
Name: id, Length: 3032, dtype: int64

In [38]:
pd.to_numeric(meta[meta['vote_count']>300]['id']).reset_index(drop=True)

0          862
1         8844
2          949
3          710
4        21032
5          524
6         4584
7            5
8         9273
9         8012
10        9691
11         451
12         902
13          63
14        9598
15         687
16        9603
17        9312
18         807
19       10530
20         629
21       10634
22         755
23        9208
24         406
25        9614
26         688
27         197
28         103
29       11000
         ...
3002    305470
3003    126889
3004    353070
3005    398929
3006    137116
3007    376134
3008    400928
3009    331214
3010    417678
3011    339846
3012    282035
3013    337339
3014    418078
3015    260514
3016    348893
3017    339403
3018    387426
3019    397422
3020    324852
3021    281338
3022    339964
3023    406990
3024    341013
3025    374720
3026    335988
3027     38286
3028    353491
3029    378236
3030    339692
3031    417870
Name: id, Length: 3032, dtype: int64

In [39]:
content_based_genres

,original_title,genres,newgenres,id
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family,862
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family,8844
2,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller,949
3,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller,710
4,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",Family Animation Adventure,21032
5,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime,524
6,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,4584
7,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy,5
8,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Adventure,9273
9,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",Comedy Thriller Crime,8012
10,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Crime Thriller,9691
11,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,451
12,La Cité des Enfants Perdus,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",Fantasy Science Fiction Adventure,902
13,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller Mystery,63
14,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",Fantasy Drama Comedy Family,9598
15,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]",Drama,687
16,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance,9603
17,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",Action Fantasy,9312
18,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",Crime Mystery Thriller,807
19,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Drama Family,10530
20,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,629
21,Friday,"[{'id': 35, 'name': 'Comedy'}]",Comedy,10634
22,From Dusk Till Dawn,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",Horror Action Thriller Crime,755
23,Broken Arrow,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Thriller,9208
24,La Haine,"[{'id': 18, 'name': 'Drama'}]",Drama,406
25,Happy Gilmore,"[{'id': 35, 'name': 'Comedy'}]",Comedy,9614
26,The Bridges of Madison County,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,688
27,Braveheart,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History War,197
28,Taxi Driver,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",Crime Drama,103
29,The Birdcage,"[{'id': 35, 'name': 'Comedy'}]",Comedy,11000
...,...,...,...,...
3002,Power Rangers,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction,305470
3003,Alien: Covenant,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",Horror Science Fiction Thriller,126889
3004,Going in Style,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Drama,353070
3005,Alibi.com,"[{'id': 35, 'name': 'Comedy'}]",Comedy,398929
3006,Smurfs: The Lost Village,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Comedy Family,137116
3007,The Discovery,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance Science Fiction Thriller,376134
3008,Gifted,"[{'id': 18, 'name': 'Drama'}]",Drama,400928
3009,Band of Brothers,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama War,331214
3010,"Everything, Everything","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,417678
3011,Baywatch,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Action Comedy,339846
3012,The Mummy,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Adventure,282035
3013,The Fate of the Furious,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Thriller,337339
3014,It Comes at Night,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",Horror Mystery Thriller,418078
3015,Cars 3,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",Family Comedy Animation Adventure,260514
3016,Boyka: Undisputed IV,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Crime,348893
3017,Baby Driver,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime,339403
3018,Okja,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",Adventure Drama Fantasy Science Fiction,387426
3019,Rough Night,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",Drama Comedy,397422
3020,Despicable Me 3,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",Action Animation Adventure Family Comedy,324852
3021,War for the Planet of the Apes,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",Drama Science Fiction War,281338
3022,Valerian and the City of a Thousand Planets,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",Adventure Science Fiction Action,339964
3023,What Happened to Monday,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller,406990
3024,Atomic Blonde,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Action Thriller,341013
3025,Dunkirk,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History Thriller War,374720
3026,Transformers: The Last Knight,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Thriller Adventure,335988
3027,Tre uomini e una gamba,"[{'id': 35, 'name': 'Comedy'}]",Comedy,38286
3028,The Dark Tower,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",Action Western Science Fiction Fantasy Horror,353491
3029,The Emoji Movie,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",Comedy Family Animation,378236
3030,Shot Caller,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,339692
3031,Girls Trip,"[{'id': 35, 'name': 'Comedy'}]",Comedy,417870

In [40]:
cb_genres_cast_crew=content_based_genres.merge(credits,on=['id'])

In [41]:
cb_genres_cast_crew.iloc[0].loc['cast']

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [42]:
len(cb_genres_cast_crew)

3032

In [43]:
def new_cast(x):
    casts = []
    x = literal_eval(x)
    for item in x:
        name = item['name'].replace(' ','')
        casts.append(name)
    return ' '.join(casts)

In [44]:
cb_genres_cast_crew['new_crew'] = cb_genres_cast_crew['crew'].apply(new_cast)

In [45]:
cb_genres_cast_crew['new_cast'] = cb_genres_cast_crew['cast'].apply(new_cast)

In [46]:
cb_genres_cast_crew

,original_title,genres,newgenres,id,cast,crew,new_crew,new_cast
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family,862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",JohnLasseter JossWhedon AndrewStanton JoelCohe...,TomHanks TimAllen DonRickles JimVarney Wallace...
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",LarryJ.Franco JonathanHensleigh JamesHorner Jo...,RobinWilliams JonathanHyde KirstenDunst Bradle...
2,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller,949,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...",MichaelMann MichaelMann ArtLinson MichaelMann ...,AlPacino RobertDeNiro ValKilmer JonVoight TomS...
3,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller,710,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",MartinCampbell IanFleming JeffreyCaine BruceFe...,PierceBrosnan SeanBean IzabellaScorupco FamkeJ...
4,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",Family Animation Adventure,21032,"[{'cast_id': 1, 'character': 'Balto (voice)', ...","[{'credit_id': '593f24b9c3a3680369002371', 'de...",StevenSpielberg KathleenKennedy RogerS.H.Schul...,KevinBacon BobHoskins BridgetFonda JimCummings...
5,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime,524,"[{'cast_id': 4, 'character': ""Sam 'Ace' Rothst...","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...",MartinScorsese BarbaraDeFina RobertRichardson ...,RobertDeNiro SharonStone JoePesci JamesWoods D...
6,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,4584,"[{'cast_id': 6, 'character': 'Marianne Dashwoo...","[{'credit_id': '52fe43cec3a36847f807101f', 'de...",AngLee JaneAusten EmmaThompson LindsayDoran Sy...,KateWinslet EmmaThompson HughGrant TomWilkinso...
7,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy,5,"[{'cast_id': 42, 'character': 'Ted the Bellhop...","[{'credit_id': '52fe420dc3a36847f800011b', 'de...",CombustibleEdison GaryFrutkoff LanceBrown Alli...,TimRoth AntonioBanderas JenniferBeals Madonna ...
8,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Adventure,9273,"[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",SteveOedekerk JackBernstein SteveOedekerk Gary...,JimCarrey IanMcNeice SimonCallow MaynardEziash...
9,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",Comedy Thriller Crime,8012,"[{'cast_id': 1, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe448dc3a36847f809c729', 'de...",BarrySonnenfeld ElmoreLeonard DannyDeVito Mich...,JohnTravolta GeneHackman ReneRusso DannyDeVito...
10,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Crime Thriller,9691,"[{'cast_id': 1, 'character': 'Robert Rath', 'c...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...",RichardDonner LillyWachowski LanaWachowski Mar...,SylvesterStallone AntonioBanderas JulianneMoor...
11,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,451,"[{'cast_id': 1, 'character': 'Ben Sanderson', ...","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...",StuartReynolds MikeFiggis MikeFiggis MikeFiggi...,NicolasCage ElisabethShue JulianSands RichardL...
12,La Cité des Enfants Perdus,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",Fantasy Science Fiction Adventure,902,"[{'cast_id': 24, 'character': 'One', 'credit_i...","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...",Jean-PierreJeunet Jean-PierreJeunet FélicieDut...,RonPerlman DominiquePinon JudithVittet DanielE...
13,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller Mystery,63,"[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",TerryGilliam DavidWebbPeoples JanetPeoples Cha...,BruceWillis MadeleineStowe BradPitt Christophe...
14,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",Fantasy Drama Comedy Family,9598,"[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",AndrewLesnie GeorgeMiller GeorgeMiller DougMit...,ChristineCavanaugh MiriamMargolyes DannyMann H...
15,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]",Drama,687,"[{'cast_id': 7, 'character': 'Sister Helen Pre...","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...",RogerDeakins TimRobbins TimRobbins TimRobbins ...,SusanSarandon SeanPenn RobertProsky RaymondJ.B...
16,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance,9603,"[{'cast_id': 8, 'character': 'Cher Horowitz', ...","[{'credit_id': '52fe4510c3a36847f80ba261', 'de...",AmyHeckerling AmyHeckerling ScottRudin BillPop...,AliciaSilverstone StaceyDash BrittanyMurphy Pa...
17,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",Action Fantasy,9312,"[{'cast_id': 1, 'character': 'Lord Rayden', 'c...","[{'credit_id': '52fe44e6c3a36847f80b0899', 'de...",PaulW.S.Anderson MartinHunter GeorgeS.Clinton ...,ChristopherLambert RobinShou LindenAshby Cary-...
18,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",Crime Mystery Thriller,807,"[{'cast_id': 17, 'character': 'Detective David...","[{'credit_id': '52fe4279c3a36847f802176f', 'de...",SuzanneSmith HowardShore MichaelKaplan ClayA.G...,BradPitt MorganFreeman GwynethPaltrow JohnC.Mc...
19,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Drama Family,10530,"[{'cast_id': 1, 'character': 'Pocahontas (voic...","[{'credit_id': '52fe43819251416c75013087', 'de...",SusannahGrant AlanMenken H.LeePeterson PhilipL...,IreneBedard MelGibson DavidOgdenStiers JohnKas...
20,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,629,"[{'cast_id': 19, 'character': 'Michael McManus...","[{'credit_id': '52fe4260c3a36847f8019a7d', 'de...",BryanSinger BryanSinger MichaelMcDonnell Rober...,StephenBaldwin GabrielByrne ChazzPalminteri Ke...
21,Friday,"[{'id': 35, 'name': 'Comedy'}]",Comedy,10634,"[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",F.GaryGray DJPooh IceCube FrankFitzpatrick Ice...,IceCube ChrisTucker NiaLong TomListerJr. JohnW...
22,From Dusk Till Dawn,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",Horror Action Thriller Crime,755,"[{'cast_id': 1, 'character': 'Seth Gecko', 'cr...","[{'credit_id': '52fe4271c3a36847f801f22d', 'de...",RobertRodriguez QuentinTarantino QuentinTarant...,GeorgeClooney QuentinTarantino HarveyKeitel Ju...
23,Broken Arrow,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Thriller,9208,"[{'cast_id': 1, 'character': ""Maj. Vic 'Deak' ...","[{'credit_id': '52fe44dcc3a36847f80ae6f9', 'de...",GrahamYost HansZimmer BillBadalato TerenceChan...,JohnTravolta ChristianSlater SamanthaMathis De...
24,La Haine,"[{'id': 18, 'name': 'Drama'}]",Drama,406,"[{'cast_id': 2, 'character': 'Vinz', 'credit_i...","[{'credit_id': '52fe423fc3a36847f800f88b', 'de...",MathieuKassovitz ChristopheRossignon GillesSac...,VincentCassel HubertKoundé SaïdTaghmaoui Abdel...
25,Happy Gilmore,"[{'id': 35, 'name': 'Comedy'}]",Comedy,9614,"[{'cast_id': 11, 'character': 'Happy Gilmore',...","[{'credit_id': '52fe4511c3a36847f80ba903', 'de...",DennisDugan TimHerlihy AdamSandler RobertSimon...,AdamSandler BenStiller ChristopherMcDonald Jul...
26,The Bridges of Madison County,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,688,"[{'cast_id': 10, 'character': 'Francesca Johns...","[{'credit_id': '52fe426ac3a36847f801cf97', 'de...",ClintEastwood RichardLaGravenese ClintEastwood...,MerylStreep ClintEastwood AnnieCorley VictorSl...
27,Braveheart,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History War,197,"[{'cast_id': 5, 'character': 'William Wallace'...","[{'credit_id': '52fe4225c3a36847f80079c1', 'de...",RandallWallace MelGibson MelGibson JamesHorner...,MelGibson CatherineMcCormack SophieMarceau Pat...
28,Taxi Driver,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",Crime Drama,103,"[{'cast_id': 5, 'character': 'Travis Bickle', ...","[{'credit_id': '52fe4218c3a36847f80037c1', 'de...",MartinScorsese JuliaPhillips MichaelPhillips M...,RobertDeNiro CybillShepherd HarveyKeitel Jodie...
29,The Birdcage,"[{'id': 35, 'name': 'Comedy'}]",Comedy,11000,"[{'cast_id': 6, 'character': 'Armand Goldman',...","[{'credit_id': '52fe43df9251416c7502172f', 'de...",MikeNichols ElaineMay MikeNichols EmmanuelLube...,RobinWilliams GeneHackman NathanLane DianneWie...
...,...,...,...,...,...,...,...,...
3002,Power Rangers,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction,305470,"[{'cast_id': 35, 'character': 'Jason Lee Scott...","[{'credit_id': '5626f795c3a3682786000ad5', 'de...",BrianCasentini RobertoOrci HaimSaban WyckGodfr...,DacreMontgomery NaomiScott RJCyler BeckyG Ludi...
3003,Alien: Covenant,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",Horror Science Fiction Thriller,126889,"[{'cast_id': 2, 'character': 'David / Walter',...","[{'credit_id': '52fe4ae9c3a368484e16d6c1', 'de...",RidleyScott DavidGiler WalterHill MarkHuffam M...,MichaelFassbender KatherineWaterston BillyCrud...
3004,Going in Style,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Drama,353070,"[{'cast_id': 0, 'character': 'Willie Davis', '...","[{'credit_id': '55c14085c3a368238c002ee3', 'de...",ZachBraff TheodoreMelfi MartinBrest EdwardCann...,MorganFreeman MichaelCaine AlanArkin JoeyKing ...
3005,Alibi.com,"[{'id': 35, 'name': 'Comedy'}]",Comedy,398929,"[{'cast_id': 1, 'character': 'Grégory Van Huff...","[{'credit_id': '574361479251413467000dd9', 'de...",PhilippeLacheau PhilippeLacheau,PhilippeLacheau ÉlodieFontan JulienArruti Tare...
3006,Smurfs: The Lost Village,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Comedy Family,137116,"[{'cast_id': 16, 'character': 'Smurfwillow (vo...","[{'credit_id': '58dddda89251411b7f003421', 'de...",KellyAsbury JordanKerner Peyo PamelaRibon Stac...,JuliaRoberts ArielWinter EllieKemper MandyPati...
3007,The Discovery,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance Science Fiction Thriller,376134,"[{'cast_id': 10, 'character': 'Will Harbor', '...","[{'credit_id': '58ae06c0c3a36861b2001db9', 'de...",DougBernheim BrendaMcNally JamesD.Stern TrishS...,JasonSegel RooneyMara RobertRedford JessePlemo...
3008,Gifted,"[{'id': 18, 'name': 'Drama'}]",Drama,400928,"[{'cast_id': 2, 'character': 'Frank Adler', 'c...","[{'credit_id': '596e66b5c3a3686b17009e7c', 'de...",BillPankow StuartDryburgh AndyCohen KarenLunde...,ChrisEvans MckennaGrace LindsayDuncan JennySla...
3009,Band of Brothers,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama War,331214,"[{'cast_id': 1, 'character': 'Lt. Richard D. W...","[{'credit_id': '56731cd9c3a368070c002fbd', 'de...",TomHanks TomHanks StevenSpielberg DavidFrankel...,DamianLewis RonLivingston FrankJohnHughes Scot...
3010,"Everything, Everything","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,417678,"[{'cast_id': 8, 'character': 'Maddy Whittier',...","[{'credit_id': '57e5d4ccc3a368220e00165b', 'de...",StellaMeghie J.MillsGoodloe NicolaYoon,AmandlaStenberg NickRobinson AnikaNoniRose Ana...
3011,Baywatch,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Action Comedy,339846,"[{'cast_id': 0, 'character': 'Mitch Buchanan',...","[{'credit_id': '591257799251414e8504abba', 'de...",DamianShannon SethGordon DaynaPink BenClerveau...,DwayneJohnson ZacEfron AlexandraDaddario Kelly...
3012,The Mummy,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Adventure,282035,"[{'cast_id': 7, 'character': 'Nick Morton', 'c...","[{'credit_id': '58b9e962c3a368668f00ced0', 'de...",LucindaSyson SarahBradshaw BobbyCohen DavidKoe...,TomCruise RussellCrowe AnnabelleWallis SofiaBo...
3013,The Fate of the Furious,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Thriller,337339,"[{'cast_id': 0, 'character': 'Dominic Toretto'...","[{'credit_id': '553ea93f92514138a900b0a5', 'de...",VinDiesel NealH.Moritz GaryScottThompson AdamN...,VinDiesel JasonStatham DwayneJohnson MichelleR...
3014,It Comes at Night,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",Horror Mystery Thriller,418078,"[{'cast_id': 0, 'character': 'Paul', 'credit_i...","[{'credit_id': '57e8c30f9251412ae3019076', 'de...",TreyEdwardShults TreyEdwardShults DavidKaplan ...,JoelEdgerton ChristopherAbbott CarmenEjogo Kel...
3015,Cars 3,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",Family Comedy Animation Adventure,260514,"[{'cast_id': 1, 'character': 'Lightning McQuee...","[{'credit_id': '577a76f9c3a3687716000419', 'de...",BrianFee KevinReher RobertL.Baird DanielGerson...,OwenWilson CristelaAlonzo ChrisCooper ArmieHam...
3016,Boyka: Undisputed IV,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Crime,348893,"[{'cast_id': 2, 'character': 'Yuri Boyka', 'cr...","[{'credit_id': '58f4d895c3a36808350247e9', 'de...",BoazDavidson BoazDavidson LesWeldon AviLerner ...,ScottAdkins TeodoraDuhovnikova AlonAboutboul J...
3017,Baby Driver,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime,339403,"[{'cast_id': 9, 'character': 'Baby', 'credit_i...","[{'credit_id': '55c58c009251417a21000e5d', 'de...",EdgarWright EdgarWright TimBevan JamesBiddle L...,AnselElgort LilyJames KevinSpacey JamieFoxx Jo...
3018,Okja,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",Adventure Drama Fantasy Science Fiction,387426,"[{'cast_id': 18, 'character': 'Lucy Mirando / ...","[{'credit_id': '57cbb037c3a3685c250098f9', 'de...",BradPitt DariusKhondji TildaSwinton BongJoon-h...,TildaSwinton PaulDano AhnSeo-hyun ByunHee-bong...
3019,Rough Night,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",Drama Comedy,397422,"[{'cast_id': 3, 'character': 'Jess Thayer', 'c...","[{'credit_id': '57e58313c3a3681be3001161', 'de...",CraigAlpert JonathanShoemaker CarolSilverman D...,ScarlettJohansson JillianBell KateMcKinnon Zoë...
3020,Despicable Me 3,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",Action Animation Adventure Family Comedy,324852,"[{'cast_id': 0, 'character': 'Gru / Dru (voice...","[{'credit_id': '57e71794c3a368222700add6', 'de...",KyleBalda PierreCoffin KenDaurio JillAmbrosino...,SteveCarell KristenWiig TreyParker MirandaCosg...
3021,War for the Planet of the Apes,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",Drama Science Fiction War,281338,"[{'cast_id': 6, 'character': 'Caesar', 'credit...","[{'credit_id': '591f036fc3a368774e036079', 'de...",WilliamHoy MichaelSeresin JamesChinlund Pierre...,AndySerkis WoodyHarrelson SteveZahn KarinKonov...
3022,Valerian and the City of a Thousand Planets,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",Adventure Science Fiction Action,339964,"[{'cast_id': 7, 'character': 'Valerian', 'cred...","[{'credit_id': '5552701e9251411487000a5e', 'de...",LucBesson LucBesson LucBesson ThierryArbogast ...,DaneDeHaan CaraDelevingne CliveOwen Rihanna Et...
3023,What Happened to Monday,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller,406990,"[{'cast_id': 0, 'character': 'Monday / Tuesday...","[{'credit_id': '5814111e92514152d502abf9', 'de...",TommyWirkola MaxBotkin JoséDavidMontero Martin...,NoomiRapace MarwanKenzari ChristianRubeck Glen...
3024,Atomic Blonde,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Action Thriller,341013,"[{'cast_id': 0, 'character': 'Lorraine Brought...","[{'credit_id': '555da697925141757e0010d8', 'de...",DavidLeitch KurtJohnstad AntonyJohnston NickMe...,CharlizeTheron JamesMcAvoy SofiaBoutella Eddie...
3025,Dunkirk,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History Thriller War,374720,"[{'cast_id': 56, 'character': 'Tommy', 'credit...","[{'credit_id': '598138b5925141519b008a5e', 'de...",HansZimmer ChristopherNolan ChristopherNolan C...,FionnWhitehead TomGlynn-Carney JackLowden Harr...
3026,Transformers: The Last Knight,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Thriller Adventure,335988,"[{'cast_id': 2, 'character': 'Cade Yeager', 'c...","[{'credit_id': '5553e38bc3a368208f000502', 'de...",AkivaGoldsman StevenS.DeKnight RobertKirkman M...,MarkWahlberg JoshDuhamel LauraHaddock AnthonyH...
3027,Tre uomini e una gamba,"[{'id': 35, 'name': 'Comedy'}]",Comedy,38286,"[{'cast_id': 19, 'character': 'Aldo', 'credit_...","[{'credit_id': '52fe46a69251416c9105b2ef', 'de...",MassimoVenier AldoBaglio GiovanniStorti MarcoP...,AldoBaglio GiovanniStorti GiacomoPoretti Marin...
3028,The Dark Tower,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",Action Western Science Fiction Fantasy Horror,353491,"[{'cast_id': 9, 'character': 'Roland Deschain'...","[{'credit_id': '5912cf71c3a36864d40533b7', 'de...",BrianGrazer AndersThomasJensen AndersThomasJen...,IdrisElba MatthewMcConaughey TomTaylor Claudia...
3029,The Emoji Movie,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",Comedy Family Animation,378236,"[{'cast_id': 2, 'character': 'Gene (voice)', '...","[{'credit_id': '5952d8f1c3a368151c025d0e', 'de...",BenWaisbren MaryHidalgo PatrickDoyle KeithBaxt...,T.J.Miller JamesCorden AnnaFaris MayaRudolph S...
3030,Shot Caller,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,339692,"[{'cast_id': 2, 'character': 'Jacob / Money', ...","[{'credit_id': '59ad5143c3a3682c0a044cd5', 'de...",MaryVernieu AntonioPinto JeffreyStott Jonathan...,NikolajCoster-Waldau JonBernthal LakeBell Omar...
3031,Girls Trip,"[{'id': 35, 'name': 'Comedy'}]",Comedy,417870,"[{'cast_id': 6, 'character': 'Ryan Pierce', 'c...","[{'credit_id': '597a1749c3a3686868015efc', 'de...",MaryVernieu DavidNewman GregGardiner WilliamPa...,ReginaHall QueenLatifah JadaPinkettSmith Tiffa...

In [47]:
cv_res_cast = CountVectorizer().fit_transform(cb_genres_cast_crew['new_cast'])
cos_sim_cast = cosine_similarity(cv_res_cast)

In [48]:
def get_recommendation_based_cast(title):
    index_to_search = cb_genres_cast_crew[cb_genres_cast_crew['original_title'] == title].index[0]
    series_similar = pd.Series(cos_sim_cast[index_to_search])
    index_similar = series_similar.sort_values(ascending=False).head(10).index
    return cb_genres_cast_crew.loc[index_similar][['original_title','new_cast']]

In [49]:
get_recommendation_based_cast('The Avengers')

,original_title,new_cast
2034,The Avengers,RobertDowneyJr. ChrisEvans MarkRuffalo ChrisHe...
1974,Thor,ChrisHemsworth NataliePortman TomHiddleston An...
2623,Avengers: Age of Ultron,RobertDowneyJr. ChrisHemsworth MarkRuffalo Chr...
2449,Captain America: The Winter Soldier,ChrisEvans SamuelL.Jackson ScarlettJohansson R...
2629,Captain America: Civil War,ChrisEvans RobertDowneyJr. ScarlettJohansson S...
1609,The Spirit,GabrielMacht ScarlettJohansson SamuelL.Jackson...
2389,Thor: The Dark World,ChrisHemsworth NataliePortman TomHiddleston An...
1571,Iron Man,RobertDowneyJr. TerrenceHoward JeffBridges Sha...
1010,S.W.A.T.,SamuelL.Jackson ColinFarrell MichelleRodriguez...
1836,Iron Man 2,RobertDowneyJr. GwynethPaltrow DonCheadle Scar...

In [50]:
cos_sim_cast_genre = (con_sim_movie * 0.6) + (cos_sim_cast *0.4)

In [51]:
def get_recomendation_based_cast_genre(title):
    df_cos_sim_cast_genre = pd.DataFrame(cos_sim_cast_genre,columns=cb_genres_cast_crew.original_title,index=cb_genres_cast_crew.original_title)
    movie_similiar = df_cos_sim_cast_genre[title]
    return movie_similiar.sort_values(ascending = False).head(10)

In [52]:
get_recomendation_based_cast_genre('Star Wars: The Force Awakens')

original_title
Star Wars: The Force Awakens    1.00000
Solomon Kane                    0.61557
Doctor Strange                  0.60000
Fantastic Four                  0.60000
Avatar                          0.60000
Superman Returns                0.60000
Superman II                     0.60000
Superman                        0.60000
Man of Steel                    0.60000
Jupiter Ascending               0.60000
Name: Star Wars: The Force Awakens, dtype: float64

In [53]:
cb_genres_cast_crew

,original_title,genres,newgenres,id,cast,crew,new_crew,new_cast
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family,862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",JohnLasseter JossWhedon AndrewStanton JoelCohe...,TomHanks TimAllen DonRickles JimVarney Wallace...
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",LarryJ.Franco JonathanHensleigh JamesHorner Jo...,RobinWilliams JonathanHyde KirstenDunst Bradle...
2,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller,949,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...",MichaelMann MichaelMann ArtLinson MichaelMann ...,AlPacino RobertDeNiro ValKilmer JonVoight TomS...
3,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller,710,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",MartinCampbell IanFleming JeffreyCaine BruceFe...,PierceBrosnan SeanBean IzabellaScorupco FamkeJ...
4,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",Family Animation Adventure,21032,"[{'cast_id': 1, 'character': 'Balto (voice)', ...","[{'credit_id': '593f24b9c3a3680369002371', 'de...",StevenSpielberg KathleenKennedy RogerS.H.Schul...,KevinBacon BobHoskins BridgetFonda JimCummings...
5,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime,524,"[{'cast_id': 4, 'character': ""Sam 'Ace' Rothst...","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...",MartinScorsese BarbaraDeFina RobertRichardson ...,RobertDeNiro SharonStone JoePesci JamesWoods D...
6,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,4584,"[{'cast_id': 6, 'character': 'Marianne Dashwoo...","[{'credit_id': '52fe43cec3a36847f807101f', 'de...",AngLee JaneAusten EmmaThompson LindsayDoran Sy...,KateWinslet EmmaThompson HughGrant TomWilkinso...
7,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy,5,"[{'cast_id': 42, 'character': 'Ted the Bellhop...","[{'credit_id': '52fe420dc3a36847f800011b', 'de...",CombustibleEdison GaryFrutkoff LanceBrown Alli...,TimRoth AntonioBanderas JenniferBeals Madonna ...
8,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Adventure,9273,"[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",SteveOedekerk JackBernstein SteveOedekerk Gary...,JimCarrey IanMcNeice SimonCallow MaynardEziash...
9,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",Comedy Thriller Crime,8012,"[{'cast_id': 1, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe448dc3a36847f809c729', 'de...",BarrySonnenfeld ElmoreLeonard DannyDeVito Mich...,JohnTravolta GeneHackman ReneRusso DannyDeVito...
10,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Crime Thriller,9691,"[{'cast_id': 1, 'character': 'Robert Rath', 'c...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...",RichardDonner LillyWachowski LanaWachowski Mar...,SylvesterStallone AntonioBanderas JulianneMoor...
11,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,451,"[{'cast_id': 1, 'character': 'Ben Sanderson', ...","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...",StuartReynolds MikeFiggis MikeFiggis MikeFiggi...,NicolasCage ElisabethShue JulianSands RichardL...
12,La Cité des Enfants Perdus,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",Fantasy Science Fiction Adventure,902,"[{'cast_id': 24, 'character': 'One', 'credit_i...","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...",Jean-PierreJeunet Jean-PierreJeunet FélicieDut...,RonPerlman DominiquePinon JudithVittet DanielE...
13,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller Mystery,63,"[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",TerryGilliam DavidWebbPeoples JanetPeoples Cha...,BruceWillis MadeleineStowe BradPitt Christophe...
14,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",Fantasy Drama Comedy Family,9598,"[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",AndrewLesnie GeorgeMiller GeorgeMiller DougMit...,ChristineCavanaugh MiriamMargolyes DannyMann H...
15,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]",Drama,687,"[{'cast_id': 7, 'character': 'Sister Helen Pre...","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...",RogerDeakins TimRobbins TimRobbins TimRobbins ...,SusanSarandon SeanPenn RobertProsky RaymondJ.B...
16,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance,9603,"[{'cast_id': 8, 'character': 'Cher Horowitz', ...","[{'credit_id': '52fe4510c3a36847f80ba261', 'de...",AmyHeckerling AmyHeckerling ScottRudin BillPop...,AliciaSilverstone StaceyDash BrittanyMurphy Pa...
17,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",Action Fantasy,9312,"[{'cast_id': 1, 'character': 'Lord Rayden', 'c...","[{'credit_id': '52fe44e6c3a36847f80b0899', 'de...",PaulW.S.Anderson MartinHunter GeorgeS.Clinton ...,ChristopherLambert RobinShou LindenAshby Cary-...
18,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",Crime Mystery Thriller,807,"[{'cast_id': 17, 'character': 'Detective David...","[{'credit_id': '52fe4279c3a36847f802176f', 'de...",SuzanneSmith HowardShore MichaelKaplan ClayA.G...,BradPitt MorganFreeman GwynethPaltrow JohnC.Mc...
19,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Drama Family,10530,"[{'cast_id': 1, 'character': 'Pocahontas (voic...","[{'credit_id': '52fe43819251416c75013087', 'de...",SusannahGrant AlanMenken H.LeePeterson PhilipL...,IreneBedard MelGibson DavidOgdenStiers JohnKas...
20,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,629,"[{'cast_id': 19, 'character': 'Michael McManus...","[{'credit_id': '52fe4260c3a36847f8019a7d', 'de...",BryanSinger BryanSinger MichaelMcDonnell Rober...,StephenBaldwin GabrielByrne ChazzPalminteri Ke...
21,Friday,"[{'id': 35, 'name': 'Comedy'}]",Comedy,10634,"[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",F.GaryGray DJPooh IceCube FrankFitzpatrick Ice...,IceCube ChrisTucker NiaLong TomListerJr. JohnW...
22,From Dusk Till Dawn,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",Horror Action Thriller Crime,755,"[{'cast_id': 1, 'character': 'Seth Gecko', 'cr...","[{'credit_id': '52fe4271c3a36847f801f22d', 'de...",RobertRodriguez QuentinTarantino QuentinTarant...,GeorgeClooney QuentinTarantino HarveyKeitel Ju...
23,Broken Arrow,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Thriller,9208,"[{'cast_id': 1, 'character': ""Maj. Vic 'Deak' ...","[{'credit_id': '52fe44dcc3a36847f80ae6f9', 'de...",GrahamYost HansZimmer BillBadalato TerenceChan...,JohnTravolta ChristianSlater SamanthaMathis De...
24,La Haine,"[{'id': 18, 'name': 'Drama'}]",Drama,406,"[{'cast_id': 2, 'character': 'Vinz', 'credit_i...","[{'credit_id': '52fe423fc3a36847f800f88b', 'de...",MathieuKassovitz ChristopheRossignon GillesSac...,VincentCassel HubertKoundé SaïdTaghmaoui Abdel...
25,Happy Gilmore,"[{'id': 35, 'name': 'Comedy'}]",Comedy,9614,"[{'cast_id': 11, 'character': 'Happy Gilmore',...","[{'credit_id': '52fe4511c3a36847f80ba903', 'de...",DennisDugan TimHerlihy AdamSandler RobertSimon...,AdamSandler BenStiller ChristopherMcDonald Jul...
26,The Bridges of Madison County,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,688,"[{'cast_id': 10, 'character': 'Francesca Johns...","[{'credit_id': '52fe426ac3a36847f801cf97', 'de...",ClintEastwood RichardLaGravenese ClintEastwood...,MerylStreep ClintEastwood AnnieCorley VictorSl...
27,Braveheart,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History War,197,"[{'cast_id': 5, 'character': 'William Wallace'...","[{'credit_id': '52fe4225c3a36847f80079c1', 'de...",RandallWallace MelGibson MelGibson JamesHorner...,MelGibson CatherineMcCormack SophieMarceau Pat...
28,Taxi Driver,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",Crime Drama,103,"[{'cast_id': 5, 'character': 'Travis Bickle', ...","[{'credit_id': '52fe4218c3a36847f80037c1', 'de...",MartinScorsese JuliaPhillips MichaelPhillips M...,RobertDeNiro CybillShepherd HarveyKeitel Jodie...
29,The Birdcage,"[{'id': 35, 'name': 'Comedy'}]",Comedy,11000,"[{'cast_id': 6, 'character': 'Armand Goldman',...","[{'credit_id': '52fe43df9251416c7502172f', 'de...",MikeNichols ElaineMay MikeNichols EmmanuelLube...,RobinWilliams GeneHackman NathanLane DianneWie...
...,...,...,...,...,...,...,...,...
3002,Power Rangers,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction,305470,"[{'cast_id': 35, 'character': 'Jason Lee Scott...","[{'credit_id': '5626f795c3a3682786000ad5', 'de...",BrianCasentini RobertoOrci HaimSaban WyckGodfr...,DacreMontgomery NaomiScott RJCyler BeckyG Ludi...
3003,Alien: Covenant,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",Horror Science Fiction Thriller,126889,"[{'cast_id': 2, 'character': 'David / Walter',...","[{'credit_id': '52fe4ae9c3a368484e16d6c1', 'de...",RidleyScott DavidGiler WalterHill MarkHuffam M...,MichaelFassbender KatherineWaterston BillyCrud...
3004,Going in Style,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Drama,353070,"[{'cast_id': 0, 'character': 'Willie Davis', '...","[{'credit_id': '55c14085c3a368238c002ee3', 'de...",ZachBraff TheodoreMelfi MartinBrest EdwardCann...,MorganFreeman MichaelCaine AlanArkin JoeyKing ...
3005,Alibi.com,"[{'id': 35, 'name': 'Comedy'}]",Comedy,398929,"[{'cast_id': 1, 'character': 'Grégory Van Huff...","[{'credit_id': '574361479251413467000dd9', 'de...",PhilippeLacheau PhilippeLacheau,PhilippeLacheau ÉlodieFontan JulienArruti Tare...
3006,Smurfs: The Lost Village,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Comedy Family,137116,"[{'cast_id': 16, 'character': 'Smurfwillow (vo...","[{'credit_id': '58dddda89251411b7f003421', 'de...",KellyAsbury JordanKerner Peyo PamelaRibon Stac...,JuliaRoberts ArielWinter EllieKemper MandyPati...
3007,The Discovery,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance Science Fiction Thriller,376134,"[{'cast_id': 10, 'character': 'Will Harbor', '...","[{'credit_id': '58ae06c0c3a36861b2001db9', 'de...",DougBernheim BrendaMcNally JamesD.Stern TrishS...,JasonSegel RooneyMara RobertRedford JessePlemo...
3008,Gifted,"[{'id': 18, 'name': 'Drama'}]",Drama,400928,"[{'cast_id': 2, 'character': 'Frank Adler', 'c...","[{'credit_id': '596e66b5c3a3686b17009e7c', 'de...",BillPankow StuartDryburgh AndyCohen KarenLunde...,ChrisEvans MckennaGrace LindsayDuncan JennySla...
3009,Band of Brothers,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama War,331214,"[{'cast_id': 1, 'character': 'Lt. Richard D. W...","[{'credit_id': '56731cd9c3a368070c002fbd', 'de...",TomHanks TomHanks StevenSpielberg DavidFrankel...,DamianLewis RonLivingston FrankJohnHughes Scot...
3010,"Everything, Everything","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,417678,"[{'cast_id': 8, 'character': 'Maddy Whittier',...","[{'credit_id': '57e5d4ccc3a368220e00165b', 'de...",StellaMeghie J.MillsGoodloe NicolaYoon,AmandlaStenberg NickRobinson AnikaNoniRose Ana...
3011,Baywatch,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Action Comedy,339846,"[{'cast_id': 0, 'character': 'Mitch Buchanan',...","[{'credit_id': '591257799251414e8504abba', 'de...",DamianShannon SethGordon DaynaPink BenClerveau...,DwayneJohnson ZacEfron AlexandraDaddario Kelly...
3012,The Mummy,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Adventure,282035,"[{'cast_id': 7, 'character': 'Nick Morton', 'c...","[{'credit_id': '58b9e962c3a368668f00ced0', 'de...",LucindaSyson SarahBradshaw BobbyCohen DavidKoe...,TomCruise RussellCrowe AnnabelleWallis SofiaBo...
3013,The Fate of the Furious,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Thriller,337339,"[{'cast_id': 0, 'character': 'Dominic Toretto'...","[{'credit_id': '553ea93f92514138a900b0a5', 'de...",VinDiesel NealH.Moritz GaryScottThompson AdamN...,VinDiesel JasonStatham DwayneJohnson MichelleR...
3014,It Comes at Night,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",Horror Mystery Thriller,418078,"[{'cast_id': 0, 'character': 'Paul', 'credit_i...","[{'credit_id': '57e8c30f9251412ae3019076', 'de...",TreyEdwardShults TreyEdwardShults DavidKaplan ...,JoelEdgerton ChristopherAbbott CarmenEjogo Kel...
3015,Cars 3,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",Family Comedy Animation Adventure,260514,"[{'cast_id': 1, 'character': 'Lightning McQuee...","[{'credit_id': '577a76f9c3a3687716000419', 'de...",BrianFee KevinReher RobertL.Baird DanielGerson...,OwenWilson CristelaAlonzo ChrisCooper ArmieHam...
3016,Boyka: Undisputed IV,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Crime,348893,"[{'cast_id': 2, 'character': 'Yuri Boyka', 'cr...","[{'credit_id': '58f4d895c3a36808350247e9', 'de...",BoazDavidson BoazDavidson LesWeldon AviLerner ...,ScottAdkins TeodoraDuhovnikova AlonAboutboul J...
3017,Baby Driver,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime,339403,"[{'cast_id': 9, 'character': 'Baby', 'credit_i...","[{'credit_id': '55c58c009251417a21000e5d', 'de...",EdgarWright EdgarWright TimBevan JamesBiddle L...,AnselElgort LilyJames KevinSpacey JamieFoxx Jo...
3018,Okja,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",Adventure Drama Fantasy Science Fiction,387426,"[{'cast_id': 18, 'character': 'Lucy Mirando / ...","[{'credit_id': '57cbb037c3a3685c250098f9', 'de...",BradPitt DariusKhondji TildaSwinton BongJoon-h...,TildaSwinton PaulDano AhnSeo-hyun ByunHee-bong...
3019,Rough Night,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",Drama Comedy,397422,"[{'cast_id': 3, 'character': 'Jess Thayer', 'c...","[{'credit_id': '57e58313c3a3681be3001161', 'de...",CraigAlpert JonathanShoemaker CarolSilverman D...,ScarlettJohansson JillianBell KateMcKinnon Zoë...
3020,Despicable Me 3,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",Action Animation Adventure Family Comedy,324852,"[{'cast_id': 0, 'character': 'Gru / Dru (voice...","[{'credit_id': '57e71794c3a368222700add6', 'de...",KyleBalda PierreCoffin KenDaurio JillAmbrosino...,SteveCarell KristenWiig TreyParker MirandaCosg...
3021,War for the Planet of the Apes,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",Drama Science Fiction War,281338,"[{'cast_id': 6, 'character': 'Caesar', 'credit...","[{'credit_id': '591f036fc3a368774e036079', 'de...",WilliamHoy MichaelSeresin JamesChinlund Pierre...,AndySerkis WoodyHarrelson SteveZahn KarinKonov...
3022,Valerian and the City of a Thousand Planets,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",Adventure Science Fiction Action,339964,"[{'cast_id': 7, 'character': 'Valerian', 'cred...","[{'credit_id': '5552701e9251411487000a5e', 'de...",LucBesson LucBesson LucBesson ThierryArbogast ...,DaneDeHaan CaraDelevingne CliveOwen Rihanna Et...
3023,What Happened to Monday,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller,406990,"[{'cast_id': 0, 'character': 'Monday / Tuesday...","[{'credit_id': '5814111e92514152d502abf9', 'de...",TommyWirkola MaxBotkin JoséDavidMontero Martin...,NoomiRapace MarwanKenzari ChristianRubeck Glen...
3024,Atomic Blonde,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Action Thriller,341013,"[{'cast_id': 0, 'character': 'Lorraine Brought...","[{'credit_id': '555da697925141757e0010d8', 'de...",DavidLeitch KurtJohnstad AntonyJohnston NickMe...,CharlizeTheron JamesMcAvoy SofiaBoutella Eddie...
3025,Dunkirk,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History Thriller War,374720,"[{'cast_id': 56, 'character': 'Tommy', 'credit...","[{'credit_id': '598138b5925141519b008a5e', 'de...",HansZimmer ChristopherNolan ChristopherNolan C...,FionnWhitehead TomGlynn-Carney JackLowden Harr...
3026,Transformers: The Last Knight,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Thriller Adventure,335988,"[{'cast_id': 2, 'character': 'Cade Yeager', 'c...","[{'credit_id': '5553e38bc3a368208f000502', 'de...",AkivaGoldsman StevenS.DeKnight RobertKirkman M...,MarkWahlberg JoshDuhamel LauraHaddock AnthonyH...
3027,Tre uomini e una gamba,"[{'id': 35, 'name': 'Comedy'}]",Comedy,38286,"[{'cast_id': 19, 'character': 'Aldo', 'credit_...","[{'credit_id': '52fe46a69251416c9105b2ef', 'de...",MassimoVenier AldoBaglio GiovanniStorti MarcoP...,AldoBaglio GiovanniStorti GiacomoPoretti Marin...
3028,The Dark Tower,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",Action Western Science Fiction Fantasy Horror,353491,"[{'cast_id': 9, 'character': 'Roland Deschain'...","[{'credit_id': '5912cf71c3a36864d40533b7', 'de...",BrianGrazer AndersThomasJensen AndersThomasJen...,IdrisElba MatthewMcConaughey TomTaylor Claudia...
3029,The Emoji Movie,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",Comedy Family Animation,378236,"[{'cast_id': 2, 'character': 'Gene (voice)', '...","[{'credit_id': '5952d8f1c3a368151c025d0e', 'de...",BenWaisbren MaryHidalgo PatrickDoyle KeithBaxt...,T.J.Miller JamesCorden AnnaFaris MayaRudolph S...
3030,Shot Caller,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,339692,"[{'cast_id': 2, 'character': 'Jacob / Money', ...","[{'credit_id': '59ad5143c3a3682c0a044cd5', 'de...",MaryVernieu AntonioPinto JeffreyStott Jonathan...,NikolajCoster-Waldau JonBernthal LakeBell Omar...
3031,Girls Trip,"[{'id': 35, 'name': 'Comedy'}]",Comedy,417870,"[{'cast_id': 6, 'character': 'Ryan Pierce', 'c...","[{'credit_id': '597a1749c3a3686868015efc', 'de...",MaryVernieu DavidNewman GregGardiner WilliamPa...,ReginaHall QueenLatifah JadaPinkettSmith Tiffa...

In [54]:
cb_genres_cast_crew['crew'].iloc[0]

'[{\'credit_id\': \'52fe4284c3a36847f8024f49\', \'department\': \'Directing\', \'gender\': 2, \'id\': 7879, \'job\': \'Director\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f4f\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12891, \'job\': \'Screenplay\', \'name\': \'Joss Whedon\', \'profile_path\': \'/dTiVsuaTVTeGmvkhcyJvKp2A5kr.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f55\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Screenplay\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f5b\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12892, \'job\': \'Screenplay\', \'name\': \'Joel Cohen\', \'profile_path\': \'/dAubAiZcvKFbboWlj7oXOkZnTSu.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f61\', \'department\': \'Writing\', \'gender\': 0, \'id\': 12893, \'job\': \'Screenplay\', \'name\': \'Alec Sokolow\', \'profile_path\': \'/v79vlRYi94BZUQnkkyznbGUZLjT.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f67\', \'department\': \'Production\', \'gender\': 1, \'id\': 12894, \'job\': \'Producer\', \'name\': \'Bonnie Arnold\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f6d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12895, \'job\': \'Executive Producer\', \'name\': \'Ed Catmull\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f73\', \'department\': \'Production\', \'gender\': 2, \'id\': 12896, \'job\': \'Producer\', \'name\': \'Ralph Guggenheim\', \'profile_path\': None}, {\'credit_id\': \'52fe4284c3a36847f8024f79\', \'department\': \'Production\', \'gender\': 2, \'id\': 12897, \'job\': \'Executive Producer\', \'name\': \'Steve Jobs\', \'profile_path\': \'/mOMP3SwD5qWQSR0ldCIByd3guTV.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f8b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 8, \'job\': \'Editor\', \'name\': \'Lee Unkrich\', \'profile_path\': \'/bdTCCXjgOV3YyaNmLGYGOxFQMOc.jpg\'}, {\'credit_id\': \'52fe4284c3a36847f8024f91\', \'department\': \'Art\', \'gender\': 2, \'id\': 7883, \'job\': \'Art Direction\', \'name\': \'Ralph Eggleston\', \'profile_path\': \'/uUfcGKDsKO1aROMpXRs67Hn6RvR.jpg\'}, {\'credit_id\': \'598331bf925141421201044b\', \'department\': \'Editing\', \'gender\': 2, \'id\': 1168870, \'job\': \'Editor\', \'name\': \'Robert Gordon\', \'profile_path\': None}, {\'credit_id\': \'5892168cc3a36809660095f9\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1552883, \'job\': \'Foley Editor\', \'name\': \'Mary Helen Leasman\', \'profile_path\': None}, {\'credit_id\': \'5531824d9251415289000945\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1453514, \'job\': \'Animation\', \'name\': \'Kim Blanchette\', \'profile_path\': None}, {\'credit_id\': \'589215969251412dcb009bf6\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414182, \'job\': \'ADR Editor\', \'name\': \'Marilyn McCoppen\', \'profile_path\': None}, {\'credit_id\': \'589217099251412dc500a018\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Orchestrator\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5693e6b29251417b0e0000e3\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1429549, \'job\': \'Color Timer\', \'name\': \'Dale E. Grahn\', \'profile_path\': None}, {\'credit_id\': \'572e2522c3a36869e6001a9c\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7949, \'job\': \'CG Painter\', \'name\': \'Robin Cooper\', \'profile_path\': None}, {\'credit_id\': \'574f12309251415ca1000012\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7879, \'job\': \'Original Story\', \'name\': \'John Lasseter\', \'profile_path\': \'/7EdqiNbr4FRjIhKHyPPdFfEEEFG.jpg\'}, {\'credit_id\': \'574f1240c3a3682e7300001c\', \'department\': \'Writing\', \'gender\': 2, \'id\': 12890, \'job\': \'Original Story\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'574f12519251415c92000015\', \'department\': \'Writing\', \'gender\': 0, \'id\': 7911, \'job\': \'Original Story\', \'name\': \'Joe Ranft\', \'profile_path\': \'/f1BoWC2JbCcfP1e5hKfGsxkHzVU.jpg\'}, {\'credit_id\': \'574f12cec3a3682e82000022\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1629419, \'job\': \'Post Production Supervisor\', \'name\': \'Patsy Bouge\', \'profile_path\': None}, {\'credit_id\': \'574f14f19251415ca1000082\', \'department\': \'Art\', \'gender\': 0, \'id\': 7961, \'job\': \'Sculptor\', \'name\': \'Norm DeCarlo\', \'profile_path\': None}, {\'credit_id\': \'5751ae4bc3a3683772002b7f\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 12905, \'job\': \'Animation Director\', \'name\': \'Ash Brannon\', \'profile_path\': \'/6ueWgPEEBHvS3De2BHYQnYjRTig.jpg\'}, {\'credit_id\': \'5891edbe9251412dc5007cd6\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Music\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'589213d39251412dc8009832\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748707, \'job\': \'Layout\', \'name\': \'Roman Figun\', \'profile_path\': None}, {\'credit_id\': \'5892173dc3a3680968009351\', \'department\': \'Sound\', \'gender\': 2, \'id\': 4949, \'job\': \'Orchestrator\', \'name\': \'Don Davis\', \'profile_path\': None}, {\'credit_id\': \'589217cec3a3686b0a0052ba\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1372885, \'job\': \'Music Editor\', \'name\': \'James Flamberg\', \'profile_path\': None}, {\'credit_id\': \'58921831c3a3686348004a64\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1739962, \'job\': \'Negative Cutter\', \'name\': \'Mary Beth Smith\', \'profile_path\': None}, {\'credit_id\': \'58921838c3a36809700096c0\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748513, \'job\': \'Negative Cutter\', \'name\': \'Rick Mackay\', \'profile_path\': None}, {\'credit_id\': \'589218429251412dd1009d1b\', \'department\': \'Art\', \'gender\': 0, \'id\': 1458006, \'job\': \'Title Designer\', \'name\': \'Susan Bradley\', \'profile_path\': None}, {\'credit_id\': \'5891ed99c3a3680966007670\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1748557, \'job\': \'Supervising Technical Director\', \'name\': \'William Reeves\', \'profile_path\': None}, {\'credit_id\': \'5891edcec3a3686b0a002eb2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7885, \'job\': \'Songs\', \'name\': \'Randy Newman\', \'profile_path\': \'/w0JzfoiM25nrnxYOzosPHRq6mlE.jpg\'}, {\'credit_id\': \'5891edf9c3a36809700075e6\', \'department\': \'Writing\', \'gender\': 2, \'id\': 7, \'job\': \'Original Story\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58920f0b9251412dd7009104\', \'department\': \'Crew\', \'gender\': 2, \'id\': 12890, \'job\': \'Supervising Animator\', \'name\': \'Pete Docter\', \'profile_path\': \'/r6ngPgnReA3RHmKjmSoVsc6Awjp.jpg\'}, {\'credit_id\': \'58920f1fc3a3680977009021\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Designer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'58920f389251412dd700912d\', \'department\': \'Production\', \'gender\': 0, \'id\': 12909, \'job\': \'Production Supervisor\', \'name\': \'Karen Robert Jackson\', \'profile_path\': None}, {\'credit_id\': \'58920fbd9251412dcb00969c\', \'department\': \'Crew\', \'gender\': 0, \'id\': 953331, \'job\': \'Executive Music Producer\', \'name\': \'Chris Montan\', \'profile_path\': None}, {\'credit_id\': \'589210069251412dd7009219\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7893, \'job\': \'Animation Director\', \'name\': \'Rich Quade\', \'profile_path\': None}, {\'credit_id\': \'589210329251412dcd00943b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8025, \'job\': \'Animation\', \'name\': \'Michael Berenstein\', \'profile_path\': None}, {\'credit_id\': \'5892103bc3a368096a009180\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 78009, \'job\': \'Animation\', \'name\': \'Colin Brady\', \'profile_path\': None}, {\'credit_id\': \'5892105dc3a3680968008db2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748682, \'job\': \'Animation\', \'name\': \'Davey Crockett Feiten\', \'profile_path\': None}, {\'credit_id\': \'589210669251412dcd009466\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454030, \'job\': \'Animation\', \'name\': \'Angie Glocka\', \'profile_path\': None}, {\'credit_id\': \'5892107c9251412dd1009613\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748683, \'job\': \'Animation\', \'name\': \'Rex Grignon\', \'profile_path\': None}, {\'credit_id\': \'5892108ac3a3680973008d3f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748684, \'job\': \'Animation\', \'name\': \'Tom K. Gurney\', \'profile_path\': None}, {\'credit_id\': \'58921093c3a3686348004477\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 8029, \'job\': \'Animation\', \'name\': \'Jimmy Hayward\', \'profile_path\': \'/lTDRpudEY7BDwTefXbXzMlmb0ui.jpg\'}, {\'credit_id\': \'5892109b9251412dcd0094b0\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1426773, \'job\': \'Animation\', \'name\': \'Hal T. Hickel\', \'profile_path\': None}, {\'credit_id\': \'589210a29251412dc5009a29\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8035, \'job\': \'Animation\', \'name\': \'Karen Kiser\', \'profile_path\': None}, {\'credit_id\': \'589210ccc3a3680977009191\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748688, \'job\': \'Animation\', \'name\': \'Anthony B. LaMolinara\', \'profile_path\': None}, {\'credit_id\': \'589210d7c3a3686b0a004c1f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 587314, \'job\': \'Animation\', \'name\': \'Guionne Leroy\', \'profile_path\': None}, {\'credit_id\': \'589210e1c3a36809770091a7\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Animation\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'589210ee9251412dc200978a\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748689, \'job\': \'Animation\', \'name\': \'Les Major\', \'profile_path\': None}, {\'credit_id\': \'589210fa9251412dc8009595\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7892, \'job\': \'Animation\', \'name\': \'Glenn McQueen\', \'profile_path\': None}, {\'credit_id\': \'589211029251412dc8009598\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 555795, \'job\': \'Animation\', \'name\': \'Mark Oftedal\', \'profile_path\': None}, {\'credit_id\': \'5892110b9251412dc800959d\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7882, \'job\': \'Animation\', \'name\': \'Jeff Pidgeon\', \'profile_path\': \'/yLddkg5HcgbJg00cS13GVBnP0HY.jpg\'}, {\'credit_id\': \'58921113c3a36863480044e4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8017, \'job\': \'Animation\', \'name\': \'Jeff Pratt\', \'profile_path\': None}, {\'credit_id\': \'5892111c9251412dcb0097e9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1184140, \'job\': \'Animation\', \'name\': \'Steve Rabatich\', \'profile_path\': None}, {\'credit_id\': \'58921123c3a36809700090f6\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8049, \'job\': \'Animation\', \'name\': \'Roger Rose\', \'profile_path\': None}, {\'credit_id\': \'5892112b9251412dcb0097fb\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1509559, \'job\': \'Animation\', \'name\': \'Steve Segal\', \'profile_path\': None}, {\'credit_id\': \'589211349251412dc80095c3\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748691, \'job\': \'Animation\', \'name\': \'Doug Sheppeck\', \'profile_path\': None}, {\'credit_id\': \'5892113cc3a3680970009106\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8050, \'job\': \'Animation\', \'name\': \'Alan Sperling\', \'profile_path\': None}, {\'credit_id\': \'58921148c3a3686b0a004c99\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8010, \'job\': \'Animation\', \'name\': \'Doug Sweetland\', \'profile_path\': None}, {\'credit_id\': \'58921150c3a3680966009125\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 8044, \'job\': \'Animation\', \'name\': \'David Tart\', \'profile_path\': None}, {\'credit_id\': \'589211629251412dc5009b00\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1454034, \'job\': \'Animation\', \'name\': \'Ken Willard\', \'profile_path\': None}, {\'credit_id\': \'589211c1c3a3686b0a004d28\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 7887, \'job\': \'Visual Effects Supervisor\', \'name\': \'Thomas Porter\', \'profile_path\': None}, {\'credit_id\': \'589211d4c3a3680968008ed9\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1406878, \'job\': \'Visual Effects\', \'name\': \'Mark Thomas Henne\', \'profile_path\': None}, {\'credit_id\': \'589211f59251412dd4008e65\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748698, \'job\': \'Visual Effects\', \'name\': \'Oren Jacob\', \'profile_path\': None}, {\'credit_id\': \'58921242c3a368096a00939b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748699, \'job\': \'Visual Effects\', \'name\': \'Darwyn Peachey\', \'profile_path\': None}, {\'credit_id\': \'5892124b9251412dc5009bd2\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748701, \'job\': \'Visual Effects\', \'name\': \'Mitch Prater\', \'profile_path\': None}, {\'credit_id\': \'58921264c3a3686b0a004dbf\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748703, \'job\': \'Visual Effects\', \'name\': \'Brian M. Rosen\', \'profile_path\': None}, {\'credit_id\': \'589212709251412dcd009676\', \'department\': \'Lighting\', \'gender\': 1, \'id\': 12912, \'job\': \'Lighting Supervisor\', \'name\': \'Sharon Calahan\', \'profile_path\': None}, {\'credit_id\': \'5892127fc3a3686b0a004de5\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 7899, \'job\': \'Lighting Supervisor\', \'name\': \'Galyn Susman\', \'profile_path\': None}, {\'credit_id\': \'589212cdc3a3680970009268\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'CG Painter\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892130f9251412dc8009791\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748705, \'job\': \'Sculptor\', \'name\': \'Shelley Daniels Lekven\', \'profile_path\': None}, {\'credit_id\': \'5892131c9251412dd4008f4c\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7889, \'job\': \'Character Designer\', \'name\': \'Bob Pauley\', \'profile_path\': None}, {\'credit_id\': \'589213249251412dd100987b\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7918, \'job\': \'Character Designer\', \'name\': \'Bud Luckey\', \'profile_path\': \'/pcCh7G19FKMNijmPQg1PMH1btic.jpg\'}, {\'credit_id\': \'5892132b9251412dc80097b1\', \'department\': \'Visual Effects\', \'gender\': 2, \'id\': 7, \'job\': \'Character Designer\', \'name\': \'Andrew Stanton\', \'profile_path\': \'/pvQWsu0qc8JFQhMVJkTHuexUAa1.jpg\'}, {\'credit_id\': \'58921332c3a368634800467b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 12915, \'job\': \'Character Designer\', \'name\': \'William Cone\', \'profile_path\': None}, {\'credit_id\': \'5892135f9251412dd4008f90\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1748706, \'job\': \'Character Designer\', \'name\': \'Steve Johnson\', \'profile_path\': None}, {\'credit_id\': \'58921384c3a3680973008fd4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1176752, \'job\': \'Character Designer\', \'name\': \'Dan Haskett\', \'profile_path\': None}, {\'credit_id\': \'5892138e9251412dc20099fc\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1088034, \'job\': \'Character Designer\', \'name\': \'Tom Holloway\', \'profile_path\': \'/a0r0T2usTBpgMI5aZbRBDW1fTl8.jpg\'}, {\'credit_id\': \'58921395c3a368097700942f\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1447465, \'job\': \'Character Designer\', \'name\': \'Jean Gillmore\', \'profile_path\': None}, {\'credit_id\': \'589213e2c3a3680973009026\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1748709, \'job\': \'Layout\', \'name\': \'Desirée Mourad\', \'profile_path\': None}, {\'credit_id\': \'589214099251412dc5009d57\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748710, \'job\': \'Set Dresser\', \'name\': "Kelly O\'Connell", \'profile_path\': None}, {\'credit_id\': \'58921411c3a3686b0a004f70\', \'department\': \'Art\', \'gender\': 0, \'id\': 1443471, \'job\': \'Set Dresser\', \'name\': \'Sonoko Konishi\', \'profile_path\': None}, {\'credit_id\': \'58921434c3a368096a00956e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1748711, \'job\': \'Set Dresser\', \'name\': \'Ann M. Rockwell\', \'profile_path\': None}, {\'credit_id\': \'5892144ac3a36809680090de\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748712, \'job\': \'Editorial Manager\', \'name\': \'Julie M. McDonald\', \'profile_path\': None}, {\'credit_id\': \'58921479c3a368096800910f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1589729, \'job\': \'Assistant Editor\', \'name\': \'Robin Lee\', \'profile_path\': None}, {\'credit_id\': \'5892148b9251412dd10099cc\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748716, \'job\': \'Assistant Editor\', \'name\': \'Tom Freeman\', \'profile_path\': None}, {\'credit_id\': \'589214959251412dcb009b1f\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748717, \'job\': \'Assistant Editor\', \'name\': \'Ada Cochavi\', \'profile_path\': None}, {\'credit_id\': \'5892149ec3a3686348004798\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1336438, \'job\': \'Assistant Editor\', \'name\': \'Dana Mulligan\', \'profile_path\': None}, {\'credit_id\': \'589214adc3a368096a0095db\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1748718, \'job\': \'Editorial Coordinator\', \'name\': \'Deirdre Morrison\', \'profile_path\': None}, {\'credit_id\': \'589214c7c3a368097700952b\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748719, \'job\': \'Production Coordinator\', \'name\': \'Lori Lombardo\', \'profile_path\': None}, {\'credit_id\': \'589214cec3a368096a009603\', \'department\': \'Production\', \'gender\': 0, \'id\': 1748720, \'job\': \'Production Coordinator\', \'name\': \'Ellen Devine\', \'profile_path\': None}, {\'credit_id\': \'589214e39251412dc8009904\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1468014, \'job\': \'Unit Publicist\', \'name\': \'Lauren Beth Strogoff\', \'profile_path\': None}, {\'credit_id\': \'58921544c3a3686b0a00507d\', \'department\': \'Sound\', \'gender\': 2, \'id\': 2216, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Rydstrom\', \'profile_path\': \'/jZpr1nVfO7lldWI0YtmP1FGw7Rj.jpg\'}, {\'credit_id\': \'5892154c9251412dd1009a56\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1425978, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Gary Summers\', \'profile_path\': None}, {\'credit_id\': \'58921555c3a36809680091bd\', \'department\': \'Sound\', \'gender\': 2, \'id\': 8276, \'job\': \'Supervising Sound Editor\', \'name\': \'Tim Holland\', \'profile_path\': None}, {\'credit_id\': \'589215c39251412dcb009c12\', \'department\': \'Sound\', \'gender\': 0, \'id\': 7069, \'job\': \'Sound Effects Editor\', \'name\': \'Pat Jackson\', \'profile_path\': None}, {\'credit_id\': \'58921698c3a368096a009788\', \'department\': \'Crew\', \'gender\': 2, \'id\': 15894, \'job\': \'Sound Design Assistant\', \'name\': \'Tom Myers\', \'profile_path\': None}, {\'credit_id\': \'589216a89251412dc2009ca4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1414177, \'job\': \'Assistant Sound Editor\', \'name\': \'J.R. 

In [55]:
def new_directed(x):
    x = literal_eval(x)
    for item in x:
        if (item['job'] == 'Director') :
            return (item['name'].replace(' ',''))

In [56]:
cb_genres_cast_crew['new_crew'] = cb_genres_cast_crew['crew'].apply(new_directed)

In [57]:
cv_res_crew = CountVectorizer().fit_transform(cb_genres_cast_crew['new_crew'])
cos_sim_crew = cosine_similarity(cv_res_crew)

In [58]:
cb_genres_cast_crew.rename(columns = {'new_crew':'Director'},inplace=True)

In [59]:
def get_recommendation_based_crew(title):
    index_to_search = cb_genres_cast_crew[cb_genres_cast_crew['original_title'] == title].index[0]
    series_similar = pd.Series(cos_sim_crew[index_to_search])
    index_similar = series_similar.sort_values(ascending=False).head(10).index
    return cb_genres_cast_crew.loc[index_similar][['original_title','new_cast','Director']]

In [60]:
get_recommendation_based_crew('Guardians of the Galaxy Vol. 2')

,original_title,new_cast,Director
2508,Guardians of the Galaxy,ChrisPratt ZoeSaldana DaveBautista VinDiesel B...,JamesGunn
2628,Guardians of the Galaxy Vol. 2,ChrisPratt ZoeSaldana DaveBautista VinDiesel B...,JamesGunn
1962,Super,RainnWilson EllenPage LivTyler KevinBacon Greg...,JamesGunn
1338,Slither,NathanFillion DonThompson ElizabethBanks Gregg...,JamesGunn
1006,Lara Croft Tomb Raider: The Cradle of Life,AngelinaJolie GerardButler NoahTaylor DjimonHo...,JandeBont
1013,Tremors,KevinBacon FredWard FinnCarter MichaelGross Re...,RonUnderwood
1012,少林足球,StephenChow NgMan-Tat PatrickTseYin ZhaoWei Wo...,StephenChow
1011,Freddy vs. Jason,RobertEnglund KenKirzinger JasonRitter MonicaK...,RonnyYu
1010,S.W.A.T.,SamuelL.Jackson ColinFarrell MichelleRodriguez...,ClarkJohnson
1009,Freaky Friday,JamieLeeCurtis LindsayLohan MarkHarmon HaroldG...,MarkWaters

In [61]:
cos_sim_cast_crew_genre = con_sim_movie * 50 + cos_sim_cast * 40 + cos_sim_crew * 10

In [62]:
def get_recomendation_based_cast_genre_crew(title):
    index_movie =cb_genres_cast_crew[cb_genres_cast_crew['original_title']==title].index[0]
    index_similiar=pd.Series(cos_sim_cast_crew_genre[index_movie]).sort_values(ascending=False).head(10).index
    return cb_genres_cast_crew[['original_title','new_cast','newgenres','Director']].iloc[index_similiar]
    df_cos_sim_cast_crew_genre = pd.DataFrame(cos_sim_cast_crew_genre,columns=cb_genres_cast_crew.original_title,index=cb_genres_cast_crew.original_title)
    movie_similiar = df_cos_sim_cast_crew_genre[title]
    return movie_similiar.sort_values(ascending = False).head(10)

In [63]:
get_recomendation_based_cast_genre_crew('Kick-Ass')

,original_title,new_cast,newgenres,Director
1826,Kick-Ass,AaronTaylor-Johnson ChloëGraceMoretz Christoph...,Action Crime,MatthewVaughn
2346,Kick-Ass 2,AaronTaylor-Johnson ChloëGraceMoretz Christoph...,Action Adventure Crime,JeffWadlow
2251,Parker,JasonStatham JenniferLopez NickNolte MichaelCh...,Action Crime,TaylorHackford
3017,Baby Driver,AnselElgort LilyJames KevinSpacey JamieFoxx Jo...,Action Crime,EdgarWright
1262,Four Brothers,MarkWahlberg TyreseGibson AndréBenjamin Garret...,Action Crime,JohnSingleton
1143,Catwoman,HalleBerry BenjaminBratt SharonStone LambertWi...,Action Crime,Pitof
1273,Domino,KeiraKnightley MickeyRourke EdgarRamírez Delro...,Action Crime,TonyScott
1238,Unleashed,JetLi MorganFreeman BobHoskins VincentRegan Dy...,Action Crime,LouisLeterrier
1033,Kill Bill: Vol. 1,UmaThurman LucyLiu VivicaA.Fox DarylHannah Dav...,Action Crime,QuentinTarantino
992,The Italian Job,MarkWahlberg CharlizeTheron EdwardNorton SethG...,Action Crime,F.GaryGray

In [64]:
cb_genres_cast_crew

,original_title,genres,newgenres,id,cast,crew,Director,new_cast
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Animation Comedy Family,862,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",JohnLasseter,TomHanks TimAllen DonRickles JimVarney Wallace...
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Adventure Fantasy Family,8844,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",JoeJohnston,RobinWilliams JonathanHyde KirstenDunst Bradle...
2,Heat,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Drama Thriller,949,"[{'cast_id': 25, 'character': 'Lt. Vincent Han...","[{'credit_id': '52fe4292c3a36847f802916d', 'de...",MichaelMann,AlPacino RobertDeNiro ValKilmer JonVoight TomS...
3,GoldenEye,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",Adventure Action Thriller,710,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426ec3a36847f801e14b', 'de...",MartinCampbell,PierceBrosnan SeanBean IzabellaScorupco FamkeJ...
4,Balto,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",Family Animation Adventure,21032,"[{'cast_id': 1, 'character': 'Balto (voice)', ...","[{'credit_id': '593f24b9c3a3680369002371', 'de...",SimonWells,KevinBacon BobHoskins BridgetFonda JimCummings...
5,Casino,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime,524,"[{'cast_id': 4, 'character': ""Sam 'Ace' Rothst...","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...",MartinScorsese,RobertDeNiro SharonStone JoePesci JamesWoods D...
6,Sense and Sensibility,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,4584,"[{'cast_id': 6, 'character': 'Marianne Dashwoo...","[{'credit_id': '52fe43cec3a36847f807101f', 'de...",AngLee,KateWinslet EmmaThompson HughGrant TomWilkinso...
7,Four Rooms,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy,5,"[{'cast_id': 42, 'character': 'Ted the Bellhop...","[{'credit_id': '52fe420dc3a36847f800011b', 'de...",AllisonAnders,TimRoth AntonioBanderas JenniferBeals Madonna ...
8,Ace Ventura: When Nature Calls,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Adventure,9273,"[{'cast_id': 1, 'character': 'Ace Ventura', 'c...","[{'credit_id': '52fe44dfc3a36847f80af28b', 'de...",SteveOedekerk,JimCarrey IanMcNeice SimonCallow MaynardEziash...
9,Get Shorty,"[{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...",Comedy Thriller Crime,8012,"[{'cast_id': 1, 'character': 'Chili Palmer', '...","[{'credit_id': '52fe448dc3a36847f809c729', 'de...",BarrySonnenfeld,JohnTravolta GeneHackman ReneRusso DannyDeVito...
10,Assassins,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Crime Thriller,9691,"[{'cast_id': 1, 'character': 'Robert Rath', 'c...","[{'credit_id': '52fe451cc3a36847f80bd145', 'de...",RichardDonner,SylvesterStallone AntonioBanderas JulianneMoor...
11,Leaving Las Vegas,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,451,"[{'cast_id': 1, 'character': 'Ben Sanderson', ...","[{'credit_id': '52fe4245c3a36847f80111c3', 'de...",MikeFiggis,NicolasCage ElisabethShue JulianSands RichardL...
12,La Cité des Enfants Perdus,"[{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...",Fantasy Science Fiction Adventure,902,"[{'cast_id': 24, 'character': 'One', 'credit_i...","[{'credit_id': '52fe428ac3a36847f8026c6f', 'de...",Jean-PierreJeunet,RonPerlman DominiquePinon JudithVittet DanielE...
13,Twelve Monkeys,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller Mystery,63,"[{'cast_id': 41, 'character': 'James Cole', 'c...","[{'credit_id': '52fe4212c3a36847f8001ac7', 'de...",TerryGilliam,BruceWillis MadeleineStowe BradPitt Christophe...
14,Babe,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",Fantasy Drama Comedy Family,9598,"[{'cast_id': 1, 'character': 'Babe the Gallant...","[{'credit_id': '52fe450fc3a36847f80b9ff7', 'de...",ChrisNoonan,ChristineCavanaugh MiriamMargolyes DannyMann H...
15,Dead Man Walking,"[{'id': 18, 'name': 'Drama'}]",Drama,687,"[{'cast_id': 7, 'character': 'Sister Helen Pre...","[{'credit_id': '52fe426ac3a36847f801cf35', 'de...",TimRobbins,SusanSarandon SeanPenn RobertProsky RaymondJ.B...
16,Clueless,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Comedy Drama Romance,9603,"[{'cast_id': 8, 'character': 'Cher Horowitz', ...","[{'credit_id': '52fe4510c3a36847f80ba261', 'de...",AmyHeckerling,AliciaSilverstone StaceyDash BrittanyMurphy Pa...
17,Mortal Kombat,"[{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...",Action Fantasy,9312,"[{'cast_id': 1, 'character': 'Lord Rayden', 'c...","[{'credit_id': '52fe44e6c3a36847f80b0899', 'de...",PaulW.S.Anderson,ChristopherLambert RobinShou LindenAshby Cary-...
18,Se7en,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",Crime Mystery Thriller,807,"[{'cast_id': 17, 'character': 'Detective David...","[{'credit_id': '52fe4279c3a36847f802176f', 'de...",DavidFincher,BradPitt MorganFreeman GwynethPaltrow JohnC.Mc...
19,Pocahontas,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Drama Family,10530,"[{'cast_id': 1, 'character': 'Pocahontas (voic...","[{'credit_id': '52fe43819251416c75013087', 'de...",MikeGabriel,IreneBedard MelGibson DavidOgdenStiers JohnKas...
20,The Usual Suspects,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,629,"[{'cast_id': 19, 'character': 'Michael McManus...","[{'credit_id': '52fe4260c3a36847f8019a7d', 'de...",BryanSinger,StephenBaldwin GabrielByrne ChazzPalminteri Ke...
21,Friday,"[{'id': 35, 'name': 'Comedy'}]",Comedy,10634,"[{'cast_id': 1, 'character': 'Craig Jones', 'c...","[{'credit_id': '52fe43999251416c75016ad5', 'de...",F.GaryGray,IceCube ChrisTucker NiaLong TomListerJr. JohnW...
22,From Dusk Till Dawn,"[{'id': 27, 'name': 'Horror'}, {'id': 28, 'nam...",Horror Action Thriller Crime,755,"[{'cast_id': 1, 'character': 'Seth Gecko', 'cr...","[{'credit_id': '52fe4271c3a36847f801f22d', 'de...",RobertRodriguez,GeorgeClooney QuentinTarantino HarveyKeitel Ju...
23,Broken Arrow,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Drama Thriller,9208,"[{'cast_id': 1, 'character': ""Maj. Vic 'Deak' ...","[{'credit_id': '52fe44dcc3a36847f80ae6f9', 'de...",JohnWoo,JohnTravolta ChristianSlater SamanthaMathis De...
24,La Haine,"[{'id': 18, 'name': 'Drama'}]",Drama,406,"[{'cast_id': 2, 'character': 'Vinz', 'credit_i...","[{'credit_id': '52fe423fc3a36847f800f88b', 'de...",MathieuKassovitz,VincentCassel HubertKoundé SaïdTaghmaoui Abdel...
25,Happy Gilmore,"[{'id': 35, 'name': 'Comedy'}]",Comedy,9614,"[{'cast_id': 11, 'character': 'Happy Gilmore',...","[{'credit_id': '52fe4511c3a36847f80ba903', 'de...",DennisDugan,AdamSandler BenStiller ChristopherMcDonald Jul...
26,The Bridges of Madison County,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,688,"[{'cast_id': 10, 'character': 'Francesca Johns...","[{'credit_id': '52fe426ac3a36847f801cf97', 'de...",ClintEastwood,MerylStreep ClintEastwood AnnieCorley VictorSl...
27,Braveheart,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History War,197,"[{'cast_id': 5, 'character': 'William Wallace'...","[{'credit_id': '52fe4225c3a36847f80079c1', 'de...",MelGibson,MelGibson CatherineMcCormack SophieMarceau Pat...
28,Taxi Driver,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",Crime Drama,103,"[{'cast_id': 5, 'character': 'Travis Bickle', ...","[{'credit_id': '52fe4218c3a36847f80037c1', 'de...",MartinScorsese,RobertDeNiro CybillShepherd HarveyKeitel Jodie...
29,The Birdcage,"[{'id': 35, 'name': 'Comedy'}]",Comedy,11000,"[{'cast_id': 6, 'character': 'Armand Goldman',...","[{'credit_id': '52fe43df9251416c7502172f', 'de...",MikeNichols,RobinWilliams GeneHackman NathanLane DianneWie...
...,...,...,...,...,...,...,...,...
3002,Power Rangers,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Action Adventure Science Fiction,305470,"[{'cast_id': 35, 'character': 'Jason Lee Scott...","[{'credit_id': '5626f795c3a3682786000ad5', 'de...",DeanIsraelite,DacreMontgomery NaomiScott RJCyler BeckyG Ludi...
3003,Alien: Covenant,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",Horror Science Fiction Thriller,126889,"[{'cast_id': 2, 'character': 'David / Walter',...","[{'credit_id': '52fe4ae9c3a368484e16d6c1', 'de...",RidleyScott,MichaelFassbender KatherineWaterston BillyCrud...
3004,Going in Style,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",Crime Comedy Drama,353070,"[{'cast_id': 0, 'character': 'Willie Davis', '...","[{'credit_id': '55c14085c3a368238c002ee3', 'de...",ZachBraff,MorganFreeman MichaelCaine AlanArkin JoeyKing ...
3005,Alibi.com,"[{'id': 35, 'name': 'Comedy'}]",Comedy,398929,"[{'cast_id': 1, 'character': 'Grégory Van Huff...","[{'credit_id': '574361479251413467000dd9', 'de...",PhilippeLacheau,PhilippeLacheau ÉlodieFontan JulienArruti Tare...
3006,Smurfs: The Lost Village,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",Adventure Animation Comedy Family,137116,"[{'cast_id': 16, 'character': 'Smurfwillow (vo...","[{'credit_id': '58dddda89251411b7f003421', 'de...",KellyAsbury,JuliaRoberts ArielWinter EllieKemper MandyPati...
3007,The Discovery,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance Science Fiction Thriller,376134,"[{'cast_id': 10, 'character': 'Will Harbor', '...","[{'credit_id': '58ae06c0c3a36861b2001db9', 'de...",CharlieMcDowell,JasonSegel RooneyMara RobertRedford JessePlemo...
3008,Gifted,"[{'id': 18, 'name': 'Drama'}]",Drama,400928,"[{'cast_id': 2, 'character': 'Frank Adler', 'c...","[{'credit_id': '596e66b5c3a3686b17009e7c', 'de...",MarcWebb,ChrisEvans MckennaGrace LindsayDuncan JennySla...
3009,Band of Brothers,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama War,331214,"[{'cast_id': 1, 'character': 'Lt. Richard D. W...","[{'credit_id': '56731cd9c3a368070c002fbd', 'de...",TomHanks,DamianLewis RonLivingston FrankJohnHughes Scot...
3010,"Everything, Everything","[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Drama Romance,417678,"[{'cast_id': 8, 'character': 'Maddy Whittier',...","[{'credit_id': '57e5d4ccc3a368220e00165b', 'de...",StellaMeghie,AmandlaStenberg NickRobinson AnikaNoniRose Ana...
3011,Baywatch,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Action Comedy,339846,"[{'cast_id': 0, 'character': 'Mitch Buchanan',...","[{'credit_id': '591257799251414e8504abba', 'de...",SethGordon,DwayneJohnson ZacEfron AlexandraDaddario Kelly...
3012,The Mummy,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Adventure,282035,"[{'cast_id': 7, 'character': 'Nick Morton', 'c...","[{'credit_id': '58b9e962c3a368668f00ced0', 'de...",AlexKurtzman,TomCruise RussellCrowe AnnabelleWallis SofiaBo...
3013,The Fate of the Furious,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime Thriller,337339,"[{'cast_id': 0, 'character': 'Dominic Toretto'...","[{'credit_id': '553ea93f92514138a900b0a5', 'de...",F.GaryGray,VinDiesel JasonStatham DwayneJohnson MichelleR...
3014,It Comes at Night,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",Horror Mystery Thriller,418078,"[{'cast_id': 0, 'character': 'Paul', 'credit_i...","[{'credit_id': '57e8c30f9251412ae3019076', 'de...",TreyEdwardShults,JoelEdgerton ChristopherAbbott CarmenEjogo Kel...
3015,Cars 3,"[{'id': 10751, 'name': 'Family'}, {'id': 35, '...",Family Comedy Animation Adventure,260514,"[{'cast_id': 1, 'character': 'Lightning McQuee...","[{'credit_id': '577a76f9c3a3687716000419', 'de...",BrianFee,OwenWilson CristelaAlonzo ChrisCooper ArmieHam...
3016,Boyka: Undisputed IV,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",Thriller Action Crime,348893,"[{'cast_id': 2, 'character': 'Yuri Boyka', 'cr...","[{'credit_id': '58f4d895c3a36808350247e9', 'de...",TodorChapkanov,ScottAdkins TeodoraDuhovnikova AlonAboutboul J...
3017,Baby Driver,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",Action Crime,339403,"[{'cast_id': 9, 'character': 'Baby', 'credit_i...","[{'credit_id': '55c58c009251417a21000e5d', 'de...",EdgarWright,AnselElgort LilyJames KevinSpacey JamieFoxx Jo...
3018,Okja,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",Adventure Drama Fantasy Science Fiction,387426,"[{'cast_id': 18, 'character': 'Lucy Mirando / ...","[{'credit_id': '57cbb037c3a3685c250098f9', 'de...",BongJoon-ho,TildaSwinton PaulDano AhnSeo-hyun ByunHee-bong...
3019,Rough Night,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",Drama Comedy,397422,"[{'cast_id': 3, 'character': 'Jess Thayer', 'c...","[{'credit_id': '57e58313c3a3681be3001161', 'de...",LuciaAniello,ScarlettJohansson JillianBell KateMcKinnon Zoë...
3020,Despicable Me 3,"[{'id': 28, 'name': 'Action'}, {'id': 16, 'nam...",Action Animation Adventure Family Comedy,324852,"[{'cast_id': 0, 'character': 'Gru / Dru (voice...","[{'credit_id': '57e71794c3a368222700add6', 'de...",KyleBalda,SteveCarell KristenWiig TreyParker MirandaCosg...
3021,War for the Planet of the Apes,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",Drama Science Fiction War,281338,"[{'cast_id': 6, 'character': 'Caesar', 'credit...","[{'credit_id': '591f036fc3a368774e036079', 'de...",MattReeves,AndySerkis WoodyHarrelson SteveZahn KarinKonov...
3022,Valerian and the City of a Thousand Planets,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",Adventure Science Fiction Action,339964,"[{'cast_id': 7, 'character': 'Valerian', 'cred...","[{'credit_id': '5552701e9251411487000a5e', 'de...",LucBesson,DaneDeHaan CaraDelevingne CliveOwen Rihanna Et...
3023,What Happened to Monday,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Science Fiction Thriller,406990,"[{'cast_id': 0, 'character': 'Monday / Tuesday...","[{'credit_id': '5814111e92514152d502abf9', 'de...",TommyWirkola,NoomiRapace MarwanKenzari ChristianRubeck Glen...
3024,Atomic Blonde,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Action Thriller,341013,"[{'cast_id': 0, 'character': 'Lorraine Brought...","[{'credit_id': '555da697925141757e0010d8', 'de...",DavidLeitch,CharlizeTheron JamesMcAvoy SofiaBoutella Eddie...
3025,Dunkirk,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Action Drama History Thriller War,374720,"[{'cast_id': 56, 'character': 'Tommy', 'credit...","[{'credit_id': '598138b5925141519b008a5e', 'de...",ChristopherNolan,FionnWhitehead TomGlynn-Carney JackLowden Harr...
3026,Transformers: The Last Knight,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Action Science Fiction Thriller Adventure,335988,"[{'cast_id': 2, 'character': 'Cade Yeager', 'c...","[{'credit_id': '5553e38bc3a368208f000502', 'de...",MichaelBay,MarkWahlberg JoshDuhamel LauraHaddock AnthonyH...
3027,Tre uomini e una gamba,"[{'id': 35, 'name': 'Comedy'}]",Comedy,38286,"[{'cast_id': 19, 'character': 'Aldo', 'credit_...","[{'credit_id': '52fe46a69251416c9105b2ef', 'de...",MassimoVenier,AldoBaglio GiovanniStorti GiacomoPoretti Marin...
3028,The Dark Tower,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",Action Western Science Fiction Fantasy Horror,353491,"[{'cast_id': 9, 'character': 'Roland Deschain'...","[{'credit_id': '5912cf71c3a36864d40533b7', 'de...",NikolajArcel,IdrisElba MatthewMcConaughey TomTaylor Claudia...
3029,The Emoji Movie,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",Comedy Family Animation,378236,"[{'cast_id': 2, 'character': 'Gene (voice)', '...","[{'credit_id': '5952d8f1c3a368151c025d0e', 'de...",AnthonyLeondis,T.J.Miller JamesCorden AnnaFaris MayaRudolph S...
3030,Shot Caller,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",Drama Crime Thriller,339692,"[{'cast_id': 2, 'character': 'Jacob / Money', ...","[{'credit_id': '59ad5143c3a3682c0a044cd5', 'de...",RicRomanWaugh,NikolajCoster-Waldau JonBernthal LakeBell Omar...
3031,Girls Trip,"[{'id': 35, 'name': 'Comedy'}]",Comedy,417870,"[{'cast_id': 6, 'character': 'Ryan Pierce', 'c...","[{'credit_id': '597a1749c3a3686868015efc', 'de...",MalcolmD.Lee,ReginaHall QueenLatifah JadaPinkettSmith Tiffa...

## Collaboration Filtering

## Item Based

In [65]:
rating = pd.read_csv('the-movies-dataset/ratings_small.csv')

In [66]:
rating.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

### Mengubah data type dari kolom id dari object ke numerik

In [67]:
index_drop=meta[meta.id.str.contains('-')].index
meta.drop(index_drop,inplace=True)

In [68]:
meta['id']=pd.to_numeric(meta['id'])

In [69]:
user_movie=rating.merge(meta,left_on='movieId',right_on='id')[['userId','original_title','movieId','rating']]

In [70]:
user_movie_pivot=user_movie.pivot_table(index='original_title',columns='userId',values='rating')

In [71]:
user_movie_pivot.dropna(thresh=10,inplace=True)
user_movie_pivot.fillna(0,inplace=True)
cos_sim_ratings=cosine_similarity(user_movie_pivot)

In [72]:
df_sim_rating=pd.DataFrame(cos_sim_ratings,index=user_movie_pivot.index,columns=user_movie_pivot.index)
df_sim_rating

original_title,...Più forte ragazzi!,10 Items or Less,12 + 1,2 Days in Paris,"20,000 Leagues Under the Sea",2001: A Space Odyssey,24 Hour Party People,25th Hour,28 Days Later,28 Weeks Later,...,隠し砦の三悪人,風の谷のナウシカ,鬼婆,거룩한 계보,괴물,밀양,빈집,사마리아,해안선,활
original_title,,,,,,,,,,,,,,,,,,,,,
...Più forte ragazzi!,1.000000,0.092714,0.097318,0.181094,0.235865,0.244670,0.240067,0.121701,0.169178,0.230018,...,0.333762,0.096447,0.163942,0.181642,0.129475,0.133230,0.184926,0.186528,0.216144,0.132112
10 Items or Less,0.092714,1.000000,0.019956,0.056941,0.176252,0.066387,0.104382,0.000000,0.029997,0.035179,...,0.104514,0.000000,0.250315,0.087069,0.000000,0.153404,0.193506,0.091845,0.144128,0.166159
12 + 1,0.097318,0.019956,1.000000,0.264195,0.013822,0.067946,0.048431,0.000000,0.080724,0.227553,...,0.008557,0.060302,0.064960,0.011542,0.000000,0.039421,0.083681,0.000000,0.148148,0.057821
2 Days in Paris,0.181094,0.056941,0.264195,1.000000,0.202731,0.069794,0.199606,0.000000,0.103251,0.254780,...,0.073862,0.114707,0.219052,0.032934,0.084542,0.168719,0.238768,0.265764,0.052839,0.164981
"20,000 Leagues Under the Sea",0.235865,0.176252,0.013822,0.202731,1.000000,0.169380,0.218390,0.049530,0.218145,0.233796,...,0.159036,0.107518,0.191733,0.123838,0.172078,0.180212,0.162485,0.261716,0.094447,0.196223
2001: A Space Odyssey,0.244670,0.066387,0.067946,0.069794,0.169380,1.000000,0.174145,0.137379,0.075987,0.229126,...,0.288613,0.211422,0.120907,0.024563,0.008697,0.048213,0.125885,0.055752,0.234641,0.103954
24 Hour Party People,0.240067,0.104382,0.048431,0.199606,0.218390,0.174145,1.000000,0.064957,0.119713,0.220135,...,0.118367,0.066198,0.219656,0.030187,0.068880,0.307381,0.296360,0.350267,0.267269,0.457855
25th Hour,0.121701,0.000000,0.000000,0.000000,0.049530,0.137379,0.064957,1.000000,0.074551,0.256424,...,0.178187,0.000000,0.180440,0.000000,0.012574,0.118962,0.098644,0.110227,0.121082,0.000000
28 Days Later,0.169178,0.029997,0.080724,0.103251,0.218145,0.075987,0.119713,0.074551,1.000000,0.200030,...,0.086954,0.072514,0.197064,0.116243,0.218233,0.213317,0.111634,0.087847,0.094642,0.069530
28 Weeks Later,0.230018,0.035179,0.227553,0.254780,0.233796,0.229126,0.220135,0.256424,0.200030,1.000000,...,0.251303,0.072952,0.228720,0.130162,0.086413,0.130808,0.082977,0.104538,0.192028,0.112420
300,0.282394,0.140760,0.142494,0.180702,0.203104,0.302367,0.324355,0.143336,0.146362,0.295519,...,0.237781,0.068742,0.217106,0.085114,0.063331,0.258393,0.210162,0.234217,0.261239,0.247174
"4 luni, 3 săptămîni și 2 zile",0.152631,0.000000,0.000000,0.274284,0.209160,0.070780,0.249983,0.167171,0.139106,0.131781,...,0.120465,0.103752,0.220300,0.121863,0.187695,0.198850,0.132524,0.164540,0.147723,0.111918
42nd Street,0.143322,0.080562,0.000000,0.000000,0.181123,0.083832,0.321785,0.000000,0.000000,0.100293,...,0.119185,0.015215,0.089401,0.000000,0.000000,0.124328,0.000000,0.176948,0.082935,0.147712
48 Hrs.,0.366354,0.097094,0.059876,0.114710,0.351611,0.327530,0.157588,0.072276,0.165604,0.194782,...,0.250445,0.120081,0.167485,0.147148,0.049954,0.152952,0.148571,0.179178,0.121463,0.117848
5 Card Stud,0.458257,0.049382,0.060046,0.098064,0.215974,0.172427,0.084029,0.087920,0.141800,0.169837,...,0.268130,0.042022,0.156212,0.222342,0.116300,0.067555,0.079884,0.082595,0.121410,0.048413
5x2,0.152275,0.037552,0.121965,0.049715,0.102409,0.090140,0.000000,0.000000,0.099522,0.168027,...,0.204509,0.063041,0.022225,0.263354,0.094088,0.000000,0.029525,0.000000,0.078406,0.000000
7 vírgenes,0.166516,0.032001,0.113833,0.190644,0.209633,0.139464,0.115056,0.059742,0.218719,0.145497,...,0.148660,0.150420,0.107325,0.107198,0.125712,0.098333,0.136984,0.230386,0.092387,0.061813
8 Mile,0.038996,0.000000,0.163846,0.077917,0.077280,0.096855,0.033064,0.054938,0.054730,0.110436,...,0.082444,0.085629,0.026125,0.062409,0.065539,0.019377,0.000000,0.028727,0.018205,0.035527
8 femmes,0.268295,0.135095,0.129542,0.289140,0.187133,0.152096,0.652077,0.063052,0.070350,0.191093,...,0.109296,0.048382,0.237201,0.033860,0.053488,0.223868,0.297407,0.298372,0.221474,0.401210
88 Minutes,0.308537,0.087830,0.151151,0.076108,0.249269,0.196390,0.190547,0.152604,0.255267,0.328456,...,0.285143,0.064340,0.225414,0.175260,0.145817,0.098578,0.096050,0.053489,0.196349,0.076344
A Bridge Too Far,0.231693,0.343866,0.032162,0.195680,0.278168,0.095237,0.174821,0.025691,0.072799,0.115352,...,0.164007,0.049284,0.154447,0.130889,0.057513,0.079203,0.242576,0.281361,0.031531,0.186071
A Brief History of Time,0.353726,0.090151,0.037937,0.301842,0.256469,0.202369,0.378212,0.079259,0.092117,0.184289,...,0.235185,0.096084,0.291284,0.094584,0.070038,0.188436,0.186266,0.239452,0.128403,0.307522
A Clockwork Orange,0.241391,0.042491,0.138992,0.166650,0.323079,0.287756,0.076911,0.112111,0.282269,0.197332,...,0.152782,0.080784,0.109867,0.078798,0.083395,0.096527,0.094378,0.046664,0.171522,0.064635
A Close Shave,0.154988,0.067886,0.141740,0.154067,0.245583,0.106488,0.235359,0.081473,0.113629,0.157476,...,0.121640,0.131872,0.111925,0.000000,0.194386,0.124522,0.173467,0.384745,0.156364,0.105371
A Kiss Before Dying,0.161632,0.053281,0.111245,0.056972,0.103787,0.070331,0.004973,0.000000,0.143206,0.108257,...,0.093851,0.061923,0.058217,0.248017,0.134635,0.007084,0.041086,0.007877,0.073213,0.008906
A Nightmare on Elm Street,0.459392,0.065864,0.143370,0.205931,0.402185,0.314623,0.179684,0.106324,0.267109,0.258804,...,0.308816,0.068459,0.217716,0.147112,0.046815,0.105192,0.137450,0.147743,0.158650,0.119906
A Perfect Murder,0.208013,0.115847,0.035834,0.153367,0.209781,0.107154,0.412608,0.113206,0.107726,0.184628,...,0.189186,0.029172,0.322820,0.090037,0.104814,0.146204,0.207467,0.272117,0.212016,0.293698
A River Runs Through It,0.302494,0.062203,0.042285,0.143632,0.293055,0.186619,0.067581,0.027344,0.225183,0.164114,...,0.178465,0.071396,0.085080,0.239397,0.128868,0.044292,0.108049,0.079432,0.023491,0.033007
A Shot in the Dark,0.129450,0.245260,0.036318,0.103626,0.230404,0.051169,0.223734,0.049319,0.039305,0.063268,...,0.095325,0.110378,0.254796,0.054328,0.174325,0.180391,0.209244,0.171923,0.048424,0.209783
A Tale of Two Cities,0.204718,0.037315,0.132737,0.098802,0.110378,0.135097,0.057019,0.201372,0.122316,0.224417,...,0.195216,0.037586,0.165637,0.161871,0.145434,0.000000,0.029339,0.000000,0.123119,0.054059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ฟ้าทะลายโจร,0.241388,0.080364,0.254796,0.159588,0.120596,0.124042,0.115575,0.065638,0.220454,0.212658,...,0.136122,0.042722,0.197188,0.077469,0.000000,0.149929,0.100043,0.164254,0.125327,0.077615
เพชฌฆาตเงียบอันตราย,0.196831,0.137032,0.137583,0.287734,0.232213,0.053234,0.109036,0.066053,0.140064,0.207192,...,0.150275,0.119923,0.273221,0.265058,0.056284,0.079876,0.118337,0.059209,0.000000,0.068342
แสงศตวรรษ,0.145147,0.231537,0.018629,0.127572,0.178669,0.053042,0.150493,0.000000,0.173614,0.146041,...,0.238287,0.040442,0.174659,0.337892,0.093891,0.074026,0.166259,0.164617,0.109292,0.093067
ゴジラ,0.301004,0.132660,0.220484,0.342077,0.191817,0.201031,0.379613,0.074853,0.125938,0.189478,...,0.117679,0.095729,0.242574,0.036074,0.088193,0.204362,0.248302,0.253323,0.304084,0.370027
ゴジラvsメカゴジラ,0.147161,0.020191,0.159262,0.026731,0.040205,0.115494,0.027223,0.000000,0.146451,0.103459,...,0.050218,0.000000,0.011950,0.048173,0.016863,0.000000,0.015875,0.000000,0.168630,0.000000
バトル・ロワイアル,0.372480,0.243317,0.084266,0.166455,0.217404,0.140558,0.194950,0.000000,0.109125,0.096789,...,0.233936,0.050423,0.244949,0.091913,0.069357,0.109812,0.159726,0.199450,0.123157,0.136612
リング,0.414315,0.169360,0.268196,0.215682,0.181366,0.211600,0.265573,0.048973,0.170498,0.251890,...,0.327440,0.063043,0.132376,0.160775,0.036898,0.089698,0.100350,0.150276,0.220935,0.154678
三枪拍案惊奇,0.156168,0.188012,0.003834,0.060175,0.159551,0.045302,0.177722,0.000000,0.021902,0.045925,...,0.113757,0.000000,0.053803,0.059749,0.000000,0.080265,0.172730,0.175466,0.062629,0.156390
巴尔扎克与小裁缝,0.140374,0.055172,0.069116,0.109561,0.144727,0.121726,0.334739,0.046350,0.189313,0.238901,...,0.141951,0.094472,0.254695,0.105305,0.122874,0.223419,0.177850,0.242360,0.174071,0.227793
座頭市,0.190097,0.175924,0.014752,0.166258,0.212769,0.154365,0.249910,0.046742,0.077164,0.124821,...,0.223044,0.105679,0.104434,0.122746,0.047795,0.109907,0.237474,0.250230,0.100311,0.233751
座頭市関所破り,0.249044,0.083636,0.004565,0.065132,0.141834,0.037522,0.078271,0.000000,0.045291,0.120008,...,0.203372,0.024777,0.110646,0.298781,0.049306,0.051021,0.101215,0.114362,0.076850,0.064145
彼女の想いで,0.089204,0.000000,0.000000,0.167358,0.206574,0.062410,0.085221,0.000000,0.088165,0.095794,...,0.065050,0.323633,0.135608,0.000000,0.211155,0.104049,0.115958,0.144614,0.073318,0.183137
怪獣総進撃,0.200866,0.031535,0.180458,0.233097,0.100105,0.114171,0.187079,0.128784,0.244860,0.316344,...,0.187966,0.021176,0.283848,0.066878,0.031214,0.152274,0.079892,0.038480,0.123557,0.076142
文雀,0.120818,0.051803,0.024035,0.068580,0.088948,0.014110,0.000000,0.084621,0.134880,0.127110,...,0.105885,0.043482,0.030659,0.325837,0.086527,0.000000,0.040729,0.000000,0.000000,0.000000
新最佳拍檔,0.198894,0.325916,0.017675,0.229045,0.224812,0.092953,0.204588,0.071118,0.164720,0.121881,...,0.181322,0.063950,0.266793,0.077116,0.169679,0.219479,0.359412,0.260307,0.170857,0.275934
暗戰,0.221704,0.097553,0.214998,0.290584,0.195305,0.180190,0.475145,0.136591,0.163287,0.366096,...,0.102489,0.114637,0.364462,0.077582,0.090526,0.252924,0.233296,0.267833,0.297980,0.417352
殯の森,0.142845,0.143060,0.013893,0.168473,0.108012,0.055052,0.069976,0.015722,0.140612,0.100844,...,0.139099,0.065346,0.057595,0.017319,0.083357,0.105153,0.173951,0.058459,0.126580,0.050608
綠草地,0.257398,0.069371,0.128748,0.206638,0.228221,0.064953,0.154327,0.000000,0.309641,0.225290,...,0.175510,0.133925,0.225815,0.052662,0.051499,0.148454,0.036362,0.063487,0.093879,0.182153
英雄,0.107511,0.017116,0.000000,0.000000,0.048900,0.234273,0.010385,0.000000,0.164734,0.000000,...,0.140922,0.237053,0.007598,0.000000,0.000000,0.000000,0.000000,0.000000,0.075445,0.013948
薔薇の葬列,0.142401,0.104669,0.080940,0.100077,0.095651,0.112456,0.128578,0.032568,0.102198,0.184649,...,0.076801,0.007809,0.154870,0.127805,0.000000,0.022973,0.140205,0.034059,0.185264,0.134786
隠し砦の三悪人,0.333762,0.104514,0.008557,0.073862,0.159036,0.288613,0.118367,0.178187,0.086954,0.251303,...,1.000000,0.141187,0.100425,0.121610,0.045868,0.077724,0.158545,0.126930,0.198534,0.088174
風の谷のナウシカ,0.096447,0.000000,0.060302,0.114707,0.107518,0.211422,0.066198,0.000000,0.072514,0.072952,...,0.141187,1.000000,0.089741,0.041762,0.128645,0.071315,0.045416,0.100440,0.053602,0.151673
鬼婆,0.163942,0.250315,0.064960,0.219052,0.191733,0.120907,0.219656,0.180440,0.197064,0.228720,...,0.100425,0.089741,1.000000,0.125148,0.082677,0.326850,0.173457,0.158415,0.122047,0.285803
거룩한 계보,0.181642,0.087069,0.011542,0.032934,0.123838,0.024563,0.030187,0.000000,0.116243,0.130162,...,0.121610,0.041762,0.125148,1.000000,0.072717,0.042998,0.063567,0.047810,0.042322,0.054059
괴물,0.129475,0.000000,0.000000,0.084542,0.172078,0.008697,0.068880,0.012574,0.218233,0.086413,...,0.045868,0.128645,0.082677,0.072717,1.000000,0.084098,0.066945,0.116885,0.059259,0.092513
밀양,0.133230,0.153404,0.039421,0.168719,0.180212,0.048213,0.307381,0.118962,0.213317,0.130808,...,0.077724,0.071315,0.326850,0.042998,0.084098,1.000000,0.162362,0.229377,0.169729,0.276941
빈집,0.184926,0.193506,0.083681,0.238768,0.162485,0.125885,0.296360,0.098644,0.111634,0.082977,...,0.158545,0.045416,0.173457,0.063567,0.066945,0.162362,1.000000,0.395102,0.164748,0.437849
사마리아,0.186528,0.091845,0.000000,0.265764,0.261716,0.055752,0.350267,0.110227,0.087847,0.104538,...,0.126930,0.100440,0.158415,0.047810,0.116885,0.229377,0.395102,1.000000,0.174110,0.307929
해안선,0.216144,0.144128,0.148148,0.052839,0.094447,0.234641,0.267269,0.121082,0.094642,0.192028,...,0.198534,0.053602,0.122047,0.042322,0.059259,0.169729,0.164748,0.174110,1.000000,0.279468
활,0.132112,0.166159,0.057821,0.164981,0.196223,0.103954,0.457855,0.000000,0.069530,0.112420,...,0.088174,0.151673,0.285803,0.054059,0.092513,0.276941,0.437849,0.307929,0.279468,1.000000

In [73]:
users = [['Titanic',5],['A Perfect Murder',2],['2 Days in Paris',4]]

In [74]:
df_sim_rating['Titanic'].sort_values(ascending=False)

original_title
Titanic                                  1.000000
Big Fish                                 0.655192
Psycho                                   0.651088
Reservoir Dogs                           0.616171
A Nightmare on Elm Street                0.607010
Monsoon Wedding                          0.606741
Rain Man                                 0.579327
Romeo + Juliet                           0.572078
Wag the Dog                              0.571416
Sissi                                    0.561254
Batman Returns                           0.546437
The Hours                                0.542332
Солярис                                  0.527823
The Conversation                         0.524053
Night on Earth                           0.523796
Back to the Future Part II               0.516263
Dave Chappelle's Block Party             0.514190
Aliens vs Predator: Requiem              0.506406
Bang Boom Bang - Ein todsicheres Ding    0.504994
Terminator 3: Rise of the Machines       0.499247
Silent Hill                              0.496009
To Kill a Mockingbird                    0.493828
48 Hrs.                                  0.491408
La passion de Jeanne d'Arc               0.486812
Love Actually                            0.482406
Syriana                                  0.472521
Trois couleurs : Rouge                   0.469431
Once Were Warriors                       0.467657
The Devil Wears Prada                    0.466177
Star Wars                                0.465735
                                           ...
Barda                                    0.065851
Pufnstuf                                 0.065534
High and Dizzy                           0.064026
괴물                                       0.063188
Die Frau mit den 5 Elefanten             0.059811
Saving Grace                             0.059657
Dracula vs. Frankenstein                 0.058734
The Driver                               0.057691
25th Hour                                0.057205
TMNT                                     0.056605
The Butter Battle Book                   0.056257
Hour of the Gun                          0.055846
Beowulf                                  0.052646
Onna no mizûmi                           0.050598
American History X                       0.050379
Hulk                                     0.049259
We're No Angels                          0.048733
Tomorrow Never Dies                      0.046434
Pink Floyd: Live at Pompeii              0.045312
The Reaping                              0.044942
MouseHunt                                0.043159
Baise-moi                                0.042915
Tueur à gages                            0.040128
Csillagosok, Katonák                     0.031048
Vesničko má středisková                  0.030922
Basquiat                                 0.030014
Lassie Come Home                         0.025319
Cesare deve morire                       0.019744
Big Time                                 0.017012
The Halliday Brand                       0.000000
Name: Titanic, Length: 943, dtype: float64

In [75]:
ser_1 = (df_sim_rating['Titanic']*(5-2.5))
ser_2 = (df_sim_rating['A Perfect Murder']*(2-2.5))
ser_3 = (df_sim_rating['2 Days in Paris']*(4-2.5))

In [76]:
(ser_1+ser_2+ser_3).sort_values(ascending=False).head(10)

original_title
Titanic                      2.730555
2 Days in Paris              1.962323
Psycho                       1.774745
A Nightmare on Elm Street    1.724984
Monsoon Wedding              1.680280
Big Fish                     1.679542
Reservoir Dogs               1.603702
Sissi                        1.597969
Rain Man                     1.572642
Wag the Dog                  1.533183
dtype: float64

In [77]:
def get_recomended_based_rating(movie):
    list_Ser=[]
    for item in movie:
        list_Ser.append(df_sim_rating[item[0]]*(item[1]-2.5))
    return sum(list_Ser).sort_values(ascending=False).head(10)

In [78]:
get_recomended_based_rating(users)

original_title
Titanic                      2.730555
2 Days in Paris              1.962323
Psycho                       1.774745
A Nightmare on Elm Street    1.724984
Monsoon Wedding              1.680280
Big Fish                     1.679542
Reservoir Dogs               1.603702
Sissi                        1.597969
Rain Man                     1.572642
Wag the Dog                  1.533183
dtype: float64

In [79]:
get_recomended_based_rating([['Batman Returns',1],['X-Men Origins: Wolverine',5],['Reservoir Dogs',1]])

original_title
X-Men Origins: Wolverine    1.577521
Romeo Must Die              0.746583
The Wedding Planner         0.663598
The Pawnshop                0.649842
Bringing Up Baby            0.616106
The Getaway                 0.605034
Good Neighbor Sam           0.586408
My Darling Clementine       0.572225
Efter brylluppet            0.569107
Blind Date                  0.568919
dtype: float64

## User Based CF

In [80]:
rating.userId.describe()

count    100004.000000
mean        347.011310
std         195.163838
min           1.000000
25%         182.000000
50%         367.000000
75%         520.000000
max         671.000000
Name: userId, dtype: float64

In [159]:
userpivot = rating.pivot_table(index='userId',columns='movieId',values='rating')

In [160]:
userpivot=userpivot.dropna(thresh=30).fillna(0)

In [87]:
user_similiarity_score=cosine_similarity(userpivot)

In [89]:
df_Similiarity = pd.DataFrame(user_similiarity_score,index=userpivot.index,columns=userpivot.index)

In [93]:
userpivot.loc[3].sort_values(ascending=False).head()

movieId
318     5.0
3949    5.0
1197    5.0
2959    5.0
356     5.0
Name: 3, dtype: float64

In [95]:
df_Similiarity.loc[2].sort_values(ascending=False).head()

userId
2      1.000000
338    0.581528
369    0.580742
151    0.573097
400    0.571252
Name: 2, dtype: float64

In [96]:
newuser=[[265,5],[266,5],[592,5],[590,5],[589,5]]

In [146]:
newuser[[i] for i in range(5)]

SyntaxError: invalid syntax (<ipython-input-146-df7326e0209e>, line 1)

In [111]:
userpivot.loc[(userpivot.index[-1]+1),[265,266,592,590,589]]=[5,5,5,5,5]

In [115]:
userpivot.loc[userpivot.index[-1]].fillna(0,inplace=True)

In [119]:
similiarity = cosine_similarity(userpivot)

In [132]:
user_id_simi=pd.DataFrame(similiarity,columns=userpivot.index,index=userpivot.index).loc[673].sort_values(ascending=False)[1:11].index

In [133]:
user_id_simi

Int64Index([2, 144, 32, 517, 354, 633, 649, 421, 440, 590], dtype='int64', name='userId')

In [134]:
serr=[]
for id in user_id_simi:
    movierating=userpivot.loc[id]
    serr.append(movierating)

In [136]:
(sum(serr)/10).sort_values(ascending=False).head()

movieId
589    4.2
590    4.2
377    4.0
480    3.7
356    3.6
dtype: float64

In [170]:
def get_recomendation_user_based(ratings):
    movie_index=np.array(ratings)[0:,0]
    movie_rating=np.array(ratings)[0:,1]
    userpivot.loc[(userpivot.index[-1]+1),movie_index] = movie_rating
    userpivot.fillna(0,inplace=True)
    similiarity= cosine_similarity(userpivot)
    user_id_sim=pd.DataFrame(similiarity,columns=userpivot.index,
                             index=userpivot.index).loc[userpivot.index[-1]].sort_values(ascending=False)[1:11].index
    ser=[]
    for id in user_id_sim:
        movie_rating=userpivot.loc[id]
        ser.append(movie_rating)
    return (sum(ser)/10).sort_values(ascending=False).drop(movie_index)

In [167]:
userpivot.tail()

movieId,1,2,3,4,5,6,7,8,9,10,...,161084,161155,161594,161830,161918,161944,162376,162542,162672,163949
userId,,,,,,,,,,,,,,,,,,,,,
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
671,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
672,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
673,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [171]:
get_recomendation_user_based([[36,5],[10,5],[205,5]])

movieId
62       2.2
296      1.9
39       1.9
595      1.8
349      1.8
593      1.8
380      1.8
457      1.8
588      1.7
454      1.6
150      1.6
364      1.6
590      1.6
592      1.6
434      1.5
480      1.5
527      1.4
225      1.4
410      1.4
153      1.4
165      1.4
339      1.4
377      1.4
260      1.3
344      1.3
318      1.3
185      1.2
300      1.2
32       1.2
141      1.2
        ...
31700    0.0
31696    0.0
31694    0.0
31689    0.0
31682    0.0
32031    0.0
31660    0.0
31658    0.0
31549    0.0
31547    0.0
31524    0.0
31522    0.0
31747    0.0
31770    0.0
31804    0.0
31878    0.0
31903    0.0
31921    0.0
31923    0.0
31930    0.0
31952    0.0
31956    0.0
31963    0.0
31973    0.0
32017    0.0
32019    0.0
32022    0.0
32025    0.0
32029    0.0
6247     0.0
Length: 9063, dtype: float64

In [151]:
print(list(userpivot.columns))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 107, 108, 110, 111, 112, 113, 114, 116, 117, 118, 119, 121, 122, 123, 124, 125, 126, 129, 130, 131, 132, 135, 137, 140, 141, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 183, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 211, 213, 214, 215, 216, 217, 218, 219, 220, 222, 223, 224, 225, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 285, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 387, 388, 389, 390, 391, 392, 393, 401, 405, 407, 408, 409, 410, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 526, 527, 528, 529, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 558, 559, 561, 562, 563, 564, 565, 567, 568, 569, 571, 573, 574, 575, 577, 580, 581, 582, 585, 586, 587, 588, 589, 590, 592, 593, 594, 595, 596, 597, 599, 600, 603, 605, 606, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 619, 620, 621, 626, 627, 628, 630, 631, 632, 633, 635, 637, 638, 639, 640, 647, 648, 650, 651, 653, 656, 659, 661, 662, 663, 664, 665, 667, 668, 670, 671, 673, 674, 678, 679, 680, 681, 685, 687, 688, 690, 691, 692, 694, 695, 696, 697, 698, 700, 702, 703, 704, 705, 707, 708, 709, 710, 711, 714, 715, 718, 719, 720, 721, 722, 724, 725, 726, 728, 731, 733, 735, 736, 737, 741, 742, 743, 745, 746, 747, 748, 750, 753, 754, 755, 756, 757, 759, 760, 761, 762, 764, 765, 766, 767, 769, 775, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 793, 798, 799, 800, 801, 802, 803, 804, 805, 806, 808, 809, 810, 813, 816, 818, 820, 824, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 844, 845, 846, 848, 849, 850, 851, 852, 854, 858, 861, 864, 865, 866, 867, 869, 870, 872, 875, 876, 879, 880, 881, 882, 885, 886, 888, 889, 891, 892, 893, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 960, 961, 962, 963, 964, 965, 966, 968, 969, 970, 971, 972, 973, 976, 980, 981, 982, 984, 986, 987, 988, 990, 991, 992, 994, 996, 997, 998, 999, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1040, 1041, 1042, 1043, 1044, 1046, 1047, 1049, 1050, 1051, 1053, 1054, 1055, 1056, 1057, 1059, 1060, 1061, 1063, 1064, 1066, 1067, 1068, 1069, 1073, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1099, 1100, 1101, 1103, 1104, 1105, 1111, 1112, 1113, 1114, 1120, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1135, 1136, 1137, 1145, 1147, 1148, 1150, 1151, 1152, 1153, 1154, 1161, 1162, 1163, 1164, 1165, 1167, 1168, 1169, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1310, 1311, 1312, 1317, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1361, 1363, 1365, 1366, 1367, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1384, 1385, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1401, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1413, 1414, 1415, 1416, 1417, 1419, 1420, 1422, 1423, 1425, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1437, 1438, 1440, 1441, 1442, 1444, 1445, 1446, 1447, 1449, 1450, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1463, 1464, 1465, 1466, 1468, 1472, 1473, 1474, 1475, 1476, 1479, 1480, 1482, 1483, 1484, 1485, 1487, 1488, 1489, 1490, 1493, 1495, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1507, 1508, 1513, 1515, 1516, 1517, 1518, 1523, 1525, 1526, 1527, 1529, 1531, 1532, 1535, 1537, 1539, 1541, 1542, 1543, 1544, 1545, 1546, 1549, 1550, 1552, 1554, 1555, 1556, 1562, 1563, 1564, 1566, 1569, 1570, 1571, 1572, 1573, 1575, 1580, 1581, 1582, 1583, 1584, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1619, 1620, 1621, 1623, 1624, 1625, 1626, 1627, 1629, 1631, 1632, 1633, 1635, 1636, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1652, 1653, 1654, 1655, 1657, 1658, 1660, 1661, 1663, 1665, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1676, 1678, 1680, 1681, 1682, 1683, 1684, 1686, 1687, 1688, 1689, 1690, 1692, 1693, 1694, 1696, 1699, 1701, 1702, 1703, 1704, 1707, 1711, 1713, 1715, 1717, 1719, 1721, 1722, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1739, 1744, 1746, 1747, 1748, 1750, 1752, 1753, 1754, 1755, 1756, 1757, 1759, 1760, 1762, 1767, 1769, 1771, 1772, 1777, 1779, 1783, 1784, 1785, 1788, 1791, 1792, 1794, 1795, 1796, 1797, 1798, 1799, 1801, 1804, 1805, 1806, 1807, 1809, 1810, 1812, 1816, 1819, 1821, 1822, 1824, 1826, 1827, 1831, 1833, 1834, 1835, 1836, 1837, 1839, 1840, 1841, 1844, 1845, 1846, 1848, 1852, 1854, 1855, 1856, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1870, 1873, 1874, 1875, 1876, 1878, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1891, 1892, 1894, 1895, 1896, 1897, 1900, 1901, 1902, 1903, 1904, 1907, 1909, 1910, 1911, 1912, 1913, 1914, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2128, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2173, 2174, 2176, 2177, 2178, 2180, 2181, 2182, 2183, 2184, 2186, 2187, 2188, 2189, 2190, 2191, 2193, 2194, 2195, 2197, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2210, 2212, 2214, 2215, 2219, 2221, 2227, 2231, 2232, 2236, 2237, 2238, 2239, 2240, 2241, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2252, 2253, 2254, 2255, 2256, 2257, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2271, 2272, 2273, 2275, 2276, 2278, 2279, 2280, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2294, 2295, 2296, 2297, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2318, 2320, 2321, 2322, 2323, 2324, 2325, 2327, 2328, 2329, 2330, 2331, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2342, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2478, 2479, 2481, 2482, 2483, 2485, 2486, 2487, 2488, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2504, 2505, 2506, 2507, 2511, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2539, 2540, 2541, 2542, 2545, 2546, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2577, 2579, 2580, 2581, 2582, 2583, 2585, 2586, 2587, 2589, 2590, 2594, 2596, 2597, 2598, 2599, 2600, 2605, 2606, 2607, 2609, 2610, 2611, 2612, 2613, 2615, 2616, 2617, 2618, 2620, 2621, 2622, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2659, 2660, 2661, 2662, 2664, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2676, 2677, 2678, 2681, 2682, 2683, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2696, 2697, 2699, 2700, 2701, 2702, 2704, 2706, 2707, 2708, 2709, 2710, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2738, 2739, 2741, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2757, 2758, 2759, 2761, 2762, 2763, 2764, 2766, 2767, 2769, 2770, 2771, 2772, 2774, 2775, 2776, 2779, 2780, 2781, 2782, 2783, 2784, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2812, 2815, 2816, 2817, 2819, 2820, 2822, 2824, 2826, 2827, 2828, 2829, 2832, 2835, 2836, 2837, 2839, 2840, 2841, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2912, 2913, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2932, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2956, 2959, 2961, 2962, 2964, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2995, 2996, 2997, 2998, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3010, 3011, 3013, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3024, 3025, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3051, 3052, 3053, 3054, 3055, 3057, 3060, 3061, 3062, 3063, 3064, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3074, 3075, 3076, 3077, 3078, 3079, 3081, 3082, 3083, 3086, 3087, 3088, 3089, 3090, 3091, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3120, 3121, 3122, 3125, 3127, 3128, 3129, 3130, 3133, 3134, 3135, 3136, 3138, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3150, 3152, 3153, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3163, 3165, 3166, 3167, 3168, 3169, 3171, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3185, 3186, 3188, 3189, 3190, 3192, 3194, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3210, 3211, 3213, 3214, 3216, 3217, 3218, 3219, 3221, 3223, 3224, 3225, 3232, 3235, 3238, 3239, 3240, 3241, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3281, 3282, 3284, 3285, 3286, 3287, 3289, 3292, 3294, 3296, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3306, 3307, 3308, 3309, 3310, 3313, 3314, 3316, 3317, 3318, 3320, 3324, 3325, 3326, 3327, 3328, 3329, 3330, 3331, 3334, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3347, 3349, 3350, 3351, 3354, 3355, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3368, 3370, 3371, 3377, 3379, 3380, 3384, 3385, 3386, 3387, 3388, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3404, 3405, 3406, 3408, 3409, 3412, 3414, 3415, 3417, 3418, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3456, 3457, 3459, 3460, 3461, 3462, 3463, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3483, 3484, 3487, 3489, 3490, 3491, 3492, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3515, 3516, 3518, 3519, 3520, 3521, 3522, 3524, 3525, 3526, 3527, 3528, 3529, 3531, 3534, 3535, 3536, 3537, 3538, 3539, 3540, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3559, 3560, 3563, 3564, 3565, 3566, 3567, 3568, 3569, 3571, 3572, 3573, 3574, 3575, 3576, 3577, 3578, 3579, 3580, 3581, 3584, 3587, 3588, 3590, 3591, 3593, 3594, 3596, 3598, 3599, 3600, 3602, 3604, 3605, 3606, 3608, 3609, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3626, 3627, 3628, 3629, 3632, 3633, 3634, 3635, 3637, 3638, 3639, 3640, 3643, 3646, 3649, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3668, 3669, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3689, 3690, 3691, 3692, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3712, 3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3744, 3745, 3746, 3747, 3751, 3752, 3753, 3754, 3755, 3757, 3758, 3759, 3760, 3761, 3763, 3764, 3765, 3766, 3768, 3769, 3770, 3771, 3773, 3774, 3775, 3777, 3780, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3794, 3795, 3798, 3799, 3800, 3801, 3802, 3804, 3805, 3806, 3807, 3809, 3810, 3811, 3812, 3813, 3814, 3816, 3819, 3820, 3821, 3822, 3823, 3824, 3825, 3826, 3827, 3829, 3831, 3832, 3833, 3834, 3835, 3836, 3837, 3838, 3839, 3840, 3841, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3851, 3852, 3854, 3855, 3857, 3858, 3859, 3860, 3861, 3863, 3864, 3865, 3868, 3869, 3870, 3871, 3872, 3873, 3875, 3877, 3879, 3880, 3882, 3883, 3885, 3886, 3889, 3890, 3891, 3892, 3893, 3895, 3896, 3897, 3900, 3901, 3902, 3903, 3905, 3906, 3908, 3909, 3910, 3911, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3927, 3928, 3929, 3930, 3932, 3933, 3934, 3936, 3937, 3938, 3939, 3940, 3941, 3942, 3943, 3945, 3946, 3947, 3948, 3949, 3950, 3951, 3952, 3953, 3955, 3956, 3957, 3959, 3960, 3961, 3962, 3963, 3964, 3965, 3966, 3967, 3968, 3969, 3970, 3971, 3972, 3973, 3975, 3976, 3977, 3978, 3979, 3980, 3981, 3983, 3984, 3985, 3986, 3987, 3988, 3989, 3990, 3991, 3992, 3993, 3994, 3996, 3997, 3998, 3999, 4000, 4001, 4002, 4003, 4005, 4006, 4007, 4008, 4009, 4010, 4011, 4012, 4014, 4015, 4016, 4017, 4018, 4019, 4020, 4021, 4022, 4023, 4024, 4025, 4026, 4027, 4029, 4030, 4031, 4033, 4034, 4035, 4036, 4037, 4039, 4040, 4041, 4042, 4043, 4045, 4046, 4047, 4048, 4051, 4052, 4053, 4054, 4055, 4056, 4060, 4061, 4062, 4063, 4066, 4067, 4068, 4069, 4073, 4076, 4077, 4079, 4080, 4081, 4082, 4084, 4085, 4086, 4088, 4089, 4090, 4091, 4092, 4095, 4098, 4101, 4102, 4103, 4104, 4105, 4106, 4108, 4109, 4111, 4114, 4115, 4116, 4117, 4121, 4122, 4123, 4124, 4126, 4128, 4130, 4131, 4132, 4133, 4135, 4136, 4139, 4140, 4141, 4142, 4143, 4144, 4146, 4148, 4149, 4151, 4153, 4155, 4156, 4158, 4159, 4161, 4162, 4166, 4167, 4168, 4169, 4171, 4173, 4174, 4175, 4177, 4178, 4179, 4180, 4181, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4194, 4195, 4197, 4198, 4200, 4201, 4203, 4205, 4207, 4208, 4210, 4211, 4212, 4213, 4214, 4215, 4216, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 4224, 4225, 4226, 4228, 4229, 4231, 4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4241, 4246, 4247, 4248, 4251, 4252, 4254, 4255, 4262, 4263, 4265, 4266, 4267, 4268, 4270, 4271, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4280, 4281, 4282, 4284, 4290, 4291, 4292, 4293, 4294, 4296, 4297, 4298, 4299, 4300, 4302, 4304, 4305, 4306, 4308, 4310, 4312, 4316, 4317, 4318, 4319, 4321, 4322, 4324, 4326, 4327, 4329, 4332, 4333, 4334, 4337, 4338, 4339, 4340, 4342, 4343, 4344, 4345, 4347, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4359, 4360, 4361, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4375, 4378, 4380, 4381, 4383, 4384, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4394, 4396, 4397, 4399, 4401, 4402, 4403, 440